In [4]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import openai

### Read the sampled dataset

In [5]:
df_items = pd.read_json('../../data/meta_Electronics_filtered_2022_2023_with_category_ratings_100_sample_1000.jsonl', lines=True)

In [6]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,HAYLOU PurFree Bone Conduction Headphones Open...,4.0,312,[Open-Ear Comfort : Haylou BC01 bone conductio...,[Open-Ear Bluetooth Bone Conduction Sport Head...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Haylou BC01', 'url': 'https://www....",HAYLOU,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '1.77 x 4.92 x 0.39 inc...,B0B1M3DGMQ,NaN,NaN,NaN
1,Computers,Xboun Kids Case for iPad Mini 5 4 3 2 (Old Mod...,4.6,103,[🍎【𝘾𝙤𝙢𝙥𝙖𝙩𝙞𝙗𝙞𝙡𝙞𝙩𝙮 】Designed exclusively for App...,[],10.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'LEDNICEKER Kids Case for iPad Mini...,Xboun,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7.9 Inches',...",B08FFYP2BF,NaN,NaN,NaN
2,Cell Phones & Accessories,ohbox USB C to Lightning Cable 3FT 2Pack USB-C...,4.5,544,[【iPhone Fast Charging Cord】The USB C to iphon...,[],13.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'The cable works well & solves the ...,ohbox,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'Ohbox', 'Connector Type': 'USB Type...",B0BY8SNST4,NaN,NaN,NaN
3,All Electronics,4 Pairs Galaxy Buds Live Ear Tips Ear Hooks Ki...,4.2,125,[【 Compatibility 】 Compatible with Samsung Gal...,[4 Pairs Galaxy Buds Live Ear Tips Ear Hooks K...,6.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Very comfortable and doesn't make ...,IiEXCEL,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '2.3 x 1.8 x 0.5 inches...,B0BJ1STN9X,NaN,NaN,NaN
4,Cell Phones & Accessories,Troniker Stylish Case for Galaxy Buds 2 Pro (2...,4.5,1093,[【High Quality Material & Perfect Size】Designe...,[],11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Convenient for ear buds! ', 'url':...",Troniker,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '2.7 x 1.8 x 0.9 inches...,B0BRSTFYHT,NaN,NaN,NaN

In [7]:
list(df_items["features"].items())[2]

(2,
 ['【iPhone Fast Charging Cord】The USB C to iphone charger cord supports a rapid charge up to 3A (max). It also support data transfer rates up to 480Mbps. Note: You need a USB-C port wall charger to match it. (including 18W, 20W, 30W, 60W, or 87W USB-C Power Adapter).',
  '【Safe USB-C Lightning Cable】The USB C Lightning cable is built into the smart chip to ensure 100% compatibility with your Apple device.No warning messages pop up and the latest C94 lightning connector is designed for fast charging.',
  '【High Quality and Ultimate Durability】USBC to lightning cable is built-in overvoltage protection and Lasts 10× longer than other cables and proven to withstand over 10,000 bends in strict laboratory tests.. Heat-resistant connector and premium nylon braided ensure complete safety and reliability.',
  '【Applicable Apple Equipment】USB-C to iPhone cable supports PD Fast Charge 3A (max) for iPhone 14 / 14 Pro/ 14 Pro Max/ 13/ 13 Pro/ 13 Pro Max/ 13 mini, iPhone 12/ 12 Mini/ 12 Pro/ 12 Pro Max/ SE 2020/ 11/ 11 Pro/ 11 Pro Max/ XS/ XS Max/ XR/ X/8/ 8 Plus, iPad, iPad Pro, iPad mini, iPad Air.',
  '【What You Get】2Pack 3ft USB-C to Lightning Cable. Worry-free 12-month warranty and friendly customer service. If you have any questions about type C to lightning cable, pls send us message or raise a QA, our service team will provide you with a satisfactory solution within 24 hours.'])

In [8]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/31iUdKtHsnL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/31iUdKtHsnL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/51IRfOhD8AL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41IK0Ux0R3L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41IK0Ux0R3L._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/6191xutgqOL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41DHkaIvLiL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41DHkaIvLiL._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/71YLn8+0IkL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41UgtydTITL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41UgtydTITL._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/71h7Bg74irL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41XEJXDk3pL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41XEJXDk3pL._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71k9nRZRD5L._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41ySAldo5uL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41ySAldo5uL._AC_.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/61CKhA+TNVL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51qbxQBccxL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51qbxQBccxL._AC_.jpg',
   'variant': 'PT07',
   'hi_res': 'https://m.media-amazon.com/images/I/81tG++DDyWL._AC_SL1500_.jpg'}])

### preprocess title and feature

In [9]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [10]:
def extract_first_large_image(row):
    return row['images'][0].get("large","")

In [11]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)

df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [12]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,All Electronics,HAYLOU PurFree Bone Conduction Headphones Open...,4.0,312,[Open-Ear Comfort : Haylou BC01 bone conductio...,HAYLOU PurFree Bone Conduction Headphones Open...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Haylou BC01', 'url': 'https://www....",HAYLOU,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '1.77 x 4.92 x 0.39 inc...,B0B1M3DGMQ,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31iUdKtHsn...
1,Computers,Xboun Kids Case for iPad Mini 5 4 3 2 (Old Mod...,4.6,103,[🍎【𝘾𝙤𝙢𝙥𝙖𝙩𝙞𝙗𝙞𝙡𝙞𝙩𝙮 】Designed exclusively for App...,Xboun Kids Case for iPad Mini 5 4 3 2 (Old Mod...,10.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'LEDNICEKER Kids Case for iPad Mini...,Xboun,"[Electronics, Computers & Accessories, Tablet ...","{'Standing screen display size': '7.9 Inches',...",B08FFYP2BF,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41yiihYpMg...
2,Cell Phones & Accessories,ohbox USB C to Lightning Cable 3FT 2Pack USB-C...,4.5,544,[【iPhone Fast Charging Cord】The USB C to iphon...,ohbox USB C to Lightning Cable 3FT 2Pack USB-C...,13.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'The cable works well & solves the ...,ohbox,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'Ohbox', 'Connector Type': 'USB Type...",B0BY8SNST4,NaN,NaN,NaN,https://m.media-amazon.com/images/I/5140l8GD20...
3,All Electronics,4 Pairs Galaxy Buds Live Ear Tips Ear Hooks Ki...,4.2,125,[【 Compatibility 】 Compatible with Samsung Gal...,4 Pairs Galaxy Buds Live Ear Tips Ear Hooks Ki...,6.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Very comfortable and doesn't make ...,IiEXCEL,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '2.3 x 1.8 x 0.5 inches...,B0BJ1STN9X,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41+Jk-9gMa...
4,Cell Phones & Accessories,Troniker Stylish Case for Galaxy Buds 2 Pro (2...,4.5,1093,[【High Quality Material & Perfect Size】Designe...,Troniker Stylish Case for Galaxy Buds 2 Pro (2...,11.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Convenient for ear buds! ', 'url':...",Troniker,"[Electronics, Headphones, Earbuds & Accessorie...",{'Product Dimensions': '2.7 x 1.8 x 0.9 inches...,B0BRSTFYHT,NaN,NaN,NaN,https://m.media-amazon.com/images/I/517vqFEpCx...

In [13]:
list(df_items["description"].items())[0]

(0,
 'HAYLOU PurFree Bone Conduction Headphones Open-Ear Bluetooth 5.2 Sport Headphones -IP67 Waterproof Wireless Earphones for Cycling and Running - CVC Dual Microphone Noise Reduction Call Open-Ear Comfort : Haylou BC01 bone conduction sound, comfortable sports wearing experience, healthier ear canal（Use bone conduction technology to receive speech, close to the bone, and the sound wave directly transmits to the auditory nerve through the bone） Safety & Connection : Stay aware and motivated through any workout with our advanced bone conduction technology. Haylou delivers quality audio while leaving your eardrums open to surroundings for ultimate safety. IP67 Waterproof Rated : Completely sweat and waterproof for workouts, fitness and running,cycling.(Not suitable for swimming.) 8 Hours of Music & Clear Calls : Enjoy eight continuous hours of music, calls and podcasts with our Bluetooth headphones. Haylou BC01 also features a 10-minute quick charge for up to 2 hours of battery life. (Magnetic Quick Charge) High Sound Quality : Bone conduction technology uses vibrations to transmit sound through your cheekbone directly to your inner ear for a premium audio experience.')

#### Sample 50 items from the dataset

In [14]:
df_sample = df_items.sample(n=50, random_state=42)

In [15]:
len(df_sample)

50

In [16]:
data_to_embed = df_sample[[ "description", "image", "rating_number", "price", "average_rating", "parent_asin"]].to_dict(orient="records")

In [17]:
data_to_embed

[{'description': 'PNY 256GB PRO Elite Class 10 U3 V30 microSDXC Flash Memory Card - 100MB/s, Class 10, U3, V30, A2, 4K UHD, Full HD, UHS-I, Micro SD & SanDisk MobileMate USB 3.0 microSD Card Reader- SDDR-B531-GN6NN Product 1: Class 10, U3, V30 speed class performance with read speeds up to 100MB/s, and write speeds up to 90MB/s for fast and smooth burst mode HD Photography and 4K Ultra HD Videography Product 1: A2 App Performance enables apps to run directly from the microSD card, delivering faster app launch and performance. A2 provides minimally 4000 IOPS (Read) and 2000 IOPS (Write) Product 1: Record and transfer videos, photos, music, files and more from microSD enabled host devices such as Android smartphones and tablets, action and surveillance cameras, drones, computers and more Product 1: Included SD adapter for compatibility with SD enabled host devices including DSLR cameras, video cameras, desktops, and laptops Product 2: Compact and durable microSD card reader Product 2: Fast UHS-I transfer speeds of up to 170 MB/s Product 2: With USB 3.0, move content up to 10x faster than USB 2.0 readers(2) Product 2: Compatible with USB 3.0 and backwards-compatible with USB 2.0',
  'image': 'https://m.media-amazon.com/images/I/31isvCjrHJL._AC_.jpg',
  'rating_number': 227,
  'price': 31.45,
  'average_rating': 4.5,
  'parent_asin': 'B08Q27PMFK'},
 {'description': 'Khanka Silicone Case Replacement for Sonos Roam Portable Smart Bluetooth Speaker (Green) Fashionable appearance design,The silicone case specially designed for Sonos Roam bluetooth speaker fits perfectly This Sonos Roam bluetooth speaker Silicone case allows you to take it outside and use it without worrying about damage when you drop it. Made of high quality TPU material to protect your Sonos Roam bluetooth speaker from bumps and scratches Compared to the traditional hard case, you can use the Sonos Roam bluetooth speaker directly without removing the silicone case Note: Only case is sold, speakers and accessories are not included',
  'image': 'https://m.media-amazon.com/images/I/41jvKbe21bL._AC_.jpg',
  'rating_number': 198,
  'price': 16.99,
  'average_rating': 4.4,
  'parent_asin': 'B0B7ML5FR1'},
 {'description': 'EGQINR Smart Watch (Answer/Make Call), 1.68" Fitness Tracker Smartwatch for Android iPhone with Blood Pressure Heart Rate Sleep Monitor Pedometer, IP67 Waterproof Smart Watches for Women 【Bluetooth Call/ AI Voice Assistant】 EGQINR smart watch with built-in high-fidelity speaker and microphone. After connecting to dual Bluetooth, you can answer/ make calls and view call records on the watch directly. Add a quick address book in FitCloudPro app. AI voice assistant, adopts a multi-analog voice interactive system, click to wake up, and speak to complete the command operation. Completely liberate hands and make your life more convenient. 【Health Monitor On The Wrist】Smart watches for women can help you monitor your physical and mental health in real time. It supports 24/7 health monitoring of blood pressure, heart rate and scientifically monitor sleep quality all night ( from 9:30 pm to 12:00 noon). There are breathing training, drinking water and sedentary reminder. In addition, it also has female health records and reminders, such as menstrual periods, pregnancy preparations, pregnancy periods, etc. 【All Day Activity Trackers】iOS android smart watch comes with 20 sport modes. It uses smart exercise data analysis to track your exercise time, heart rate, calories, steps, distance and speed in real time. Record data while exercising to get a clearer picture of your fitness trajectory. It also supports playing music while exercising. IP67 waterproof smartwatches meet your daily hand washing or wearing in rainy days. NOTE: Can not soak in the water for a long time, as well as deep diving and hot baths. 【1.68" Large Color Display】Smart watch for android phones adopt newly upgraded Realtek 8762DK to provide a smoother operation. 1.68-inch curved colorful touch screen, 240*280 pixels bringing you a more clearer and wider visual enjoyment, making every message clearer. Smart watch for iphone compatible has a rotating side button, which can directly switch dials, scroll up and down, zoom icons, and quickly double-click to switch 10 different menu styles, making the operation more easier. 【More Useful Functions】It supports editing time directly on the watch. Receive notifications of SMS, and text (Instagram, Twitter, WhatsApp, etc), *but can NOT reply messages. More useful functions like music control, weather, find phone/ watch, stopwatch, timer, alarm, games, receipt code, social code, calculator, NFC door card. If you have any problems, please feel free to contact us and we will reply you as soon as possible. Find order---Contact seller',
  'image': 'https://m.media-amazon.com/images/I/41IROOUXvoL._AC_.jpg',
  'rating_number': 439,
  'price': 89.97,
  'average_rating': 3.9,
  'parent_asin': 'B0BTBTPSZL'},
 {'description': 'Pipishell Full Motion TV Wall Mount Bracket for Most 26-60 Inch LED, LCD, OLED Flat Curved TVs up to 77lbs, Dual Articulating Arms Swivel Extension Tilt Rotation TV Mount, Max VESA 400x400mm Universal TV Compatibility - Compatible with most 26-60 inch TV of major TV brands including LG, Sharp, Sony, Panasonic, Toshiba, Philips, Thomson and more as long as VESA standard mounting holes from 100x100mm - 400x400mm, weight less than 77lbs. Please check the VESA pattern, weight, size of your TV before purchasing. Can be mounted to 8" to 16" wood stud walls and concrete/brick walls. Full Motion Flexibility for Viewing - This tv wall mount features Swivels 45° left to right so you can choose the most comfortable viewing angle, tilts 5° up and 15° down to eliminate annoying glare & reduce neck or eye strain. Extends out to 15.12" from the wall so you can move your TV into the perfect position when needed. It retracts 3" to the wall to save space while giving you a slim, sleek appearance. It allows for ±3° rotation adjustment to ensure a level display. Heavy-Duty Arms: - This TV wall mount bracket with ultra-strong 6 arms can seucurely hold your TV in place on wall . We are so confident in the construction, strength and durability of this wall bracket. It will keep your new TV safety. Quick and Easy Installation - With complete hardware provided, 1-2-3 simple installation way and friendly detailed English graphical installation guide that is actually useful (and even funny) which helps you to install this full motion TV wall mount without any hassle. Excellent Customer Service - Still worry about input blocking? VESA compatibility? No idea of the suitable mount, etc. Contact us now and find the perfect TV wall bracket.',
  'image': 'https://m.media-amazon.com/images/I/41CVyZ7j0vL._AC_.jpg',
  'rating_number': 446,
  'price': 47.99,
  'average_rating': 4.6,
  'parent_asin': 'B09R3V9DY7'},
 {'description': '420+ Miles Range TV Antenna, Digital TV Antenna for Smart TV and Old TVs, Amplified HD Antenna for TV Indoor Outdoor with Amplifier and Signal Booster-38ft Coax Cable - Support 4K 1080p ',
  'image': 'https://m.media-amazon.com/images/I/41WC6mCnLeL._AC_.jpg',
  'rating_number': 106,
  'price': nan,
  'average_rating': 3.2,
  'parent_asin': 'B0BQ6L2KMZ'},
 {'description': 'USB Type C to 3.5mm Earbuds Jack Adapter,USB Type C to 3.5mm Headphone Aux Audio Jack Hi-Res DAC Dongle Cable Compatible with Samsung Galaxy S23 S22 S21 S20 Note 20 10,Google,Black 🎧 [Wide Compatibility]:These USB C to aux headphone adapters have been designed for Samsung Galaxy S23/S23 Ultra/S22+/S22 Ultra/A53 5G/A54/A34/A33/S21+/ S21 Ultra/ S20+/ S20 Ultra/ S20 FE/ Note 20 Ultra/ Note 10/ TAB S8/S7/S6/S5/ Z Fold, Google Pixel 7 Pro/ 6 Pro/ 6a/ 2/3/4/5 and XL, Pad Pro 11/12.9, MacBook Pro/Air, Huawei Mate 10/20/30/P40/P20/P30 🎧 [HiFi Audio Adapter]: We work with Realtek to deliver a powerful integrated DAC chip that enables Hi-Fi sound from up to 384 kHz to 32-bit, while others enable 16-bit/48 kHz. The usb c to klinke adapter perfectly converts analog to digital signals, make sure you capture every note signal 🎧 [Music and calls]: This handy usb c to klinke adapter supports music playback and phone calls for most USB-C devices. Easy plug and play, USB C aux adapter, very easy to use! (NOTE: For USB-C smartphones with a 3.5mm audio port, the adapter may not support calls, NOTE: It does not support volume control for Mac.) 🎧 [More stable and flexible]: This adapter usb c to klinke is plug-and-play. No drive required. Unlock the world of hi-fi audio for you anytime, anywhere. Celebrated silhouettes reconstructed with new details. High-quality ABS shell and TPE wire materials ensure more than 25000-fold bending and prevent damage from tangling and scratching 🎧 [What You Get]:We offer this USB C to 3.5mm headphone jack adapter with a lifetime warranty and friendly 24/7 customer service.',
  'image': 'https://m.media-amazon.com/images/I/41pJqHx-8HL._AC_.jpg',
  'rating_number': 768,
  'price': 4.99,
  'average_rating': 4.3,
  'parent_asin': 'B0BQPSY1X4'},
 {'description': 'MOSTOS ; Brings Superior® - Camera Lens Caps for All Camera Models and Sizes (55mm, for Canon) Compatiable For Canon Camera Ø49mm Camera Lens and Other Lenses with 49mm Filter Thread. Your camera\'s lens thread size will be marked somewhere on the lens barrel or printed underneath your lens cap. This number is always proceeded by a "Ø" (diameter) symbol. For example: Ø49=49mm lens thread size. Made of high impact plastic for extra durability.Snap-on center pinch design allows easy attachment and removal, even with a lens hood in place.Truly good quality lens cap bundle to protect your lens from water, dust, scratches and losses. Package Include: 1 Piece Camera Lens Cap. ***PLEASE NOTE: This is not a original lens cap***',
  'image': 'https://m.media-amazon.com/images/I/31E5HeGBo2L._AC_.jpg',
  'rating_number': 856,
  'price': nan,
  'average_rating': 4.2,
  'parent_asin': 'B09LM1MJRB'},
 {'description': "LC-dolida Bluetooth Ear Warmers Winter Music Earmuffs Bluetooth Ear Muffs Built-in HD Speakers Wireless Ear Muffs Headphones Gifts for Men Women Kids for Skating Skiing Hiking ♫ HD High Fidelity Sound Music Experience- You can enjoy enhanced music listening experience with advanced digital sound by bluetooth ear muffs while staying your ear muffs. Delivered by high performance stereo loudspeaker driver, bluetooth ear muffs for men women allows you to focus on favorite music and answer calls. Bluetooth earmuffs fashion style design makes it a ideal gift or cool tech gadgets for men, women, boys, girls as a birthday gift, Christmas gifts, Thanksgiving Day's gift. ♫ Bluetooth V5.2 Wireless Technology- The Latest Bluetooth V5.2 chipset strongly enhances audio and communications. The bluetooth ear muffs for men women connects stably with cell phones, tablets, laptop and other Bluetooth enabled devices up to 30 feet (10 meters) away.The simple 3-button Panel built-in stereo speaker and microphone, makes this musical knit cap easy to answer calls, play music, adjust volume without touching the phone ♫ Soft, Comfortable& Warm - Outside is high quality soft material, inside is comfortable plush .The bluetooth ear muffs ear warmers will keep you comfortable and warm all the winter. Shield the wind from ears without blocking sound. Perfect for cold winter casual, hiking, biking, skiing, hunting ♫ Longest Battery Life- With the built-in rechargeable Li-Ion battery, bluetooth ear muffs for men women are able to continuously play music more than 10 hours (depending on the volume and the distance from the source device) a quick charge of only 1-2 hours (Micro USB charging cable included) ♫ Foldable & Washable- Bluetooth ear muffs for winter men women fit all sizes and shapes, foldable adjustable, convenient and lightweight, portable. fully washable after removing the bluetooth control module and speakers out from both two ear pocket. Please make sure the bluetooth module is in the left when wearing",
  'image': 'https://m.media-amazon.com/images/I/51Gpje2QDbL._AC_.jpg',
  'rating_number': 1310,
  'price': 24.99,
  'average_rating': 4.3,
  'parent_asin': 'B08QS12HXF'},
 {'description': 'Photo Storage for Phone Flash Drive 256GB, Memory Stick for Phone by LOMYGUS Compatible iOS and USB-c of MacBook USB3.0 of Computer(Pink 256GB) ',
  'image': 'https://m.media-amazon.com/images/I/41xn79rygdL._AC_.jpg',
  'rating_number': 148,
  'price': nan,
  'average_rating': 4.0,
  'parent_asin': 'B09T2QN1NG'},
 {'description': 'NVK USB Charger Cable 2 in 1 for Dog Training Collar and Remote, 2.6Ft USB Magnetic Charging and Micro USB Cable 【USB 2-In-1 Charger】: This 2 in 1 dog collar charger can charge the nvk shock collars for dog and remote at the same time, which can save your time. The length of charging cable is 2.6ft 【Fast Charger for E-collar】: The dual charger ensures that your bark collar and remote syncing and charging at the same time. NVK Charger Cable 2 in 1 provides a much faster charging and data exchange than other regular cables, protects your e-collar and remote from damage 【Convenient Design】: Lightweight and slim design, you could put the nvk charging cable in your bag or pockets, convenient to take out , expecially fits for the outside back up charging cord in car or traveling 【Wide Compatibility】: USB charger cable for electric dog collar works with power bank, wall charger, car charger, laptop and PC USB port. It can be a good choice as a shock collar charger replacement when your charging cable was damaged or missing 【What You Get】: 2.6Ft NVK dog collar and remote charger with USB micro and magnetic port, 12-month warranty, friendly customer service and 24 hours prompt reply. Note: When charging the devices at the same time, the display on the NVK remote control will show the charging status of the remote control, but not the charging status of the collar, and the red light on the collar will turn green when charging is completed. The charging plug is NOT included',
  'image': 'https://m.media-amazon.com/images/I/419CQJ0W07L._AC_.jpg',
  'rating_number': 232,
  'price': 19.99,
  'average_rating': 4.5,
  'parent_asin': 'B09WTM6SP3'},
 {'description': 'Beelink SER5 Mini PC with AMD Ryzen 5 5500U (6C/12T, Up to 4.0GHz) 16GB DDR4 RAM 500GB M.2 2280 NVMe SSD Mini Desktop Computer Support 4K@60Hz Triple Display, WiFi 6, BT5.2, HDMI+DP 【Superior Hardware】: Equipped with AMD Ryzen 5 5500U, 2.1GHz main frequency, 4.0GHz turbo frequency, L3 cache 8MB. With 6 cores and 12 threads, it provides more powerful comprehensive performance, releases more productivity, quickly responds to multitasking, and meets the needs of various applications such as work, entertainment, games, etc. 【Large Memory Capacity】: Built-in 16GB RAM single card slot can be upgraded to 32GB, dual card slot up to 64GB. And 500GB M.2 SSD NVME 2280 (upgradeable to 2TB), additionally can add up to 2TB 7mm 2.5 inch HDD. The large-capacity memory makes you not afraid of the complexity and arduousness of work. 【Faster Transfer Speed】: WiFi 6 supports more and faster terminals than WiFi 5, the tri-band is no longer congested, and data transmission is more stable and efficient. The speed of work file transfer, entertainment chasing drama, and online game has been fully upgraded. Bluetooth 5.2 has lower latency, more stable and efficient. 【4K & Triple Display】: Built-in 7-core AMD Radeon graphics (1800 MHz), the powerful graphics performance can not only play mainstream games, but also provide excellent performance for content creation such as video encoding. Mini PC can be connected to 3 screens via HDMI port, DP port and Type-C port for more game images and information at the same time. 【More Functions】: Mini PC is compatible with Linux and Ubuntu systems, you can choose according to your habits. Rich interface, expand the function of the computer according to your imagination.',
  'image': 'https://m.media-amazon.com/images/I/415obva1zJL._AC_.jpg',
  'rating_number': 349,
  'price': 259.0,
  'average_rating': 4.3,
  'parent_asin': 'B0BFVSM2LX'},
 {'description': 'Grifobes for Samsung Galaxy Tab A7 Lite Case, 8.7 inch Shockproof Rugged Protective Cover with Stand for 2021 Tab A7 Lite 8.7" Tablet SM-T220/T225/T227U for Kids Boys Children(Blue+Black) [Compatibility]- Grifobes shockproof tablet case is only compatible with Samsung Galaxy Tab A7 Lite 8.7 inch 2021 Release (SM-T220/T225/T227U) [Shockproof Rugged Design]- Grifobes samsung galaxy tab a7 lite case is made of high quality flexible Silicone and durable hard PC provides a perfect Military Grade Protection to your galaxy tab a7 lite case against scratches and accidental drops, bumps, shock. [Functional Kickstand]- Choose optimal viewing and typing positions (2 Mode) based on your needs that allows easy access to your favorite shows, movies, and games while on the go when taking samsung tab a7 lite case. [Precise Cutouts]- It\'s easy to access all buttons, speakers, cameras and sensors, all the ports are where they should be. Grifobes tab a7 lite case is also worth offering a practical gift choice for children, students too. [3 Months Warranty] We provide 24-hour respond and 3-month refund or replacement. Do not hesitate to contact us if you have any questions for this samsung a7 lite case.',
  'image': 'https://m.media-amazon.com/images/I/41SkZ4S4C+L._AC_.jpg',
  'rating_number': 1440,
  'price': 25.99,
  'average_rating': 4.6,
  'parent_asin': 'B09WN2S2VT'},
 {'description': 'Beelink SER5 Mini PC with AMD Ryzen 5 5500U (6C/12T, Up to 4.0GHz) 16GB DDR4 RAM 500GB M.2 2280 NVMe SSD Mini Desktop Computer Support 4K@60Hz Triple Display, WiFi 6, BT5.2, HDMI+DP 【Superior Hardware】: Equipped with AMD Ryzen 5 5500U, 2.1GHz main frequency, 4.0GHz turbo frequency, L3 cache 8MB. With 6 cores and 12 threads, it provides more powerful comprehensive performance, releases more productivity, quickly responds to multitasking, and meets the needs of various applications such as work, entertainment, games, etc. 【Large Memory Capacity】: Built-in 16GB RAM single card slot can be upgraded to 32GB, dual card slot up to 64GB. And 500GB M.2 SSD NVME 2280 (upgradeable to 2TB), additionally can add up to 2TB 7mm 2.5 inch HDD. The large-capacity memory makes you not afraid of the complexity and arduousness of work. 【Faster Transfer Speed】: WiFi 6 supports more and faster terminals than WiFi 5, the tri-band is no longer congested, and data transmission is more stable and efficient. The speed of work file transfer, entertainment chasing drama, and online game has been fully upgraded. Bluetooth 5.2 has lower latency, more stable and efficient. 【4K & Triple Display】: Built-in 7-core AMD Radeon graphics (1800 MHz), the powerful graphics performance can not only play mainstream games, but also provide excellent performance for content creation such as video encoding. Mini PC can be connected to 3 screens via HDMI port, DP port and Type-C port for more game images and information at the same time. 【More Functions】: Mini PC is compatible with Linux and Ubuntu systems, you can choose according to your habits. Rich interface, expand the function of the computer according to your imagination.',
  'image': 'https://m.media-amazon.com/images/I/415obva1zJL._AC_.jpg',
  'rating_number': 349,
  'price': 259.0,
  'average_rating': 4.3,
  'parent_asin': 'B0BFVSM2LX'},

### Define embedding function

In [ ]:
from openai import OpenAI

client = OpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama",  
)

In [35]:
def get_embedding(text, model="nomic-embed-text"):
    safe_text = text[:10000]
    response = client.embeddings.create(
        input=safe_text,
        model=model
    )
    return response.data[0].embedding

In [22]:
get_embedding("This is a sample description for embedding.")

[-0.00948325078934431,
 0.012058141641318798,
 0.027258556336164474,
 -0.05333848297595978,
 -0.00197103270329535,
 -0.01828557625412941,
 -0.026689395308494568,
 -0.020734688267111778,
 0.027556661516427994,
 0.01653590053319931,
 0.03787371143698692,
 -0.002093489747494459,
 0.03336760401725769,
 0.008175315335392952,
 -0.015481525100767612,
 0.003441209439188242,
 -0.019416728988289833,
 -0.05459068715572357,
 -0.03769243136048317,
 -0.04583422467112541,
 -0.04796198010444641,
 0.020276710391044617,
 -0.0745227262377739,
 -0.017317868769168854,
 -0.015847085043787956,
 0.03982369229197502,
 0.039216477423906326,
 0.03783240541815758,
 0.06001000106334686,
 -0.009964903816580772,
 0.002223898656666279,
 0.03785277530550957,
 0.0012547960504889488,
 -0.05744506046175957,
 -0.006924338173121214,
 -0.006462203338742256,
 0.04315252602100372,
 -0.048255693167448044,
 -0.017380185425281525,
 -0.04144918546080589,
 0.011150099337100983,
 0.002850027522072196,
 0.0482356883585453,
 -0.04788336530327797,
 -0.05741036683320999,
 0.0005746546084992588,
 0.03210902586579323,
 -0.014518295414745808,
 0.013209976255893707,
 -0.03972760587930679,
 0.012333331629633904,
 0.00018908618949353695,
 -0.0037038717418909073,
 -0.026760201901197433,
 0.024434853345155716,
 -0.02053077146410942,
 -0.01771901361644268,
 -0.019388357177376747,
 -0.024289753288030624,
 0.03219548240303993,
 0.031001731753349304,
 0.006292041856795549,
 0.04318604990839958,
 -0.07863274216651917,
 -0.012635793536901474,
 -0.0023903357796370983,
 -0.03957638144493103,
 0.017494220286607742,
 -0.027335241436958313,
 -0.015464157797396183,
 -0.03535633534193039,
 -0.01219868939369917,
 -0.018207816407084465,
 -0.03162885829806328,
 -0.02320607751607895,
 -0.01287612784653902,
 -0.010895436629652977,
 -0.004307047929614782,
 -0.015212482772767544,
 0.035079225897789,
 0.018904181197285652,
 0.028758510947227478,
 0.0027208656538277864,
 0.0015358629170805216,
 -0.04243661090731621,
 -0.03997265547513962,
 0.008622960187494755,
 0.01416836678981781,
 0.022410336881875992,
 -0.02856268920004368,
 -0.016190633177757263,
 0.05974656343460083,
 -0.016070101410150528,
 0.03870896250009537,
 -0.015582592226564884,
 0.004434223286807537,
 -0.02101636864244938,
 0.036060966551303864,
 -0.00108792120590806,
 0.03382252901792526,
 0.059683747589588165,
 0.05600687861442566,
 0.00902065820991993,
 0.05620715394616127,
 -0.06347155570983887,
 0.04076037555932999,
 0.015918007120490074,
 -0.010999005287885666,
 -0.04575864225625992,
 -0.018091591075062752,
 0.012281165458261967,
 -0.00994543731212616,
 0.015495635569095612,
 -0.023462790995836258,
 -0.04132119566202164,
 0.01185164600610733,
 0.0027273232117295265,
 0.018645061179995537,
 0.0029385352972894907,
 0.008828774094581604,
 -0.05182182043790817,
 0.018374362960457802,
 -0.023188484832644463,
 -0.064976267516613,
 -0.002197731053456664,
 0.002361263381317258,
 0.0014176280237734318,
 0.0394088551402092,
 -0.043541599065065384,
 0.0123300114646554,
 0.019280394539237022,
 0.007367542013525963,
 0.03494850546121597,
 0.0343194380402565,
 -0.043453313410282135,
 -0.0035958504304289818,
 -0.017188964411616325,
 0.017652306705713272,
 0.01973084919154644,
 0.004233216401189566,
 0.00012792884081136435,
 -0.0033467700704932213,
 -0.04356851056218147,
 0.07676228135824203,
 -0.0023094560019671917,
 0.01661752723157406,
 -0.0066398149356245995,
 -0.03521810099482536,
 -0.03237039968371391,
 0.05275474861264229,
 0.008593091741204262,
 -0.019066350534558296,
 0.02150386944413185,
 0.006900661159306765,
 -0.031129589304327965,
 -0.007405301555991173,
 -0.008619368076324463,
 0.003927921876311302,
 -0.02416241355240345,
 -0.014501923695206642,
 0.022911371663212776,
 0.008903970941901207,
 -0.019886061549186707,
 0.07212807983160019,
 -0.04554568603634834,
 0.017394395545125008,
 -0.05779493227601051,
 -0.003800417063757777,
 -0.04030710458755493,
 -0.021645009517669678,
 -0.001952784019522369,
 0.02605360560119152,
 0.02630717121064663,
 -0.03206295520067215,
 -0.015708062797784805,
 0.01673293299973011,
 0.013827499933540821,
 0.015243100933730602,
 0.06961426138877869,
 -0.0006085060886107385,
 0.000607311783824116,
 -0.031115293502807617,
 0.025553695857524872,
 0.019456490874290466,
 -0.03440721705555916,
 -0.003591081127524376,
 -0.027301223948597908,
 0.011538781225681305,
 -0.02402608096599579,
 0.02000110223889351,
 0.01272676419466734,
 0.04620828852057457,
 -0.024081602692604065,
 0.02662939950823784,
 0.0018956545973196626,
 0.01716887392103672,
 -0.030780773609876633,
 0.002343713538721204,
 -0.02850966341793537,
 -0.07027877867221832,
 -0.0322122797369957,
 -0.008456483483314514,
 -0.026099354028701782,
 -0.0015656932955607772,
 -0.021442029625177383,
 -0.0034903299529105425,
 -0.007487535942345858,
 0.07180003821849823,
 -0.03392038866877556,
 0.014345556497573853,
 0.024131428450345993,
 -0.01775391213595867,
 -0.002766686026006937,
 -0.010109427385032177,
 0.05021846666932106,
 -0.02335124835371971,
 -0.008128576911985874,
 0.04314495995640755,
 0.003221027087420225,
 0.006394787225872278,
 -0.008992751128971577,
 0.029497897252440453,
 0.015318159945309162,
 0.009907458908855915,
 -0.014666746370494366,
 -0.016365036368370056,
 -0.007258111145347357,
 0.04916340485215187,
 -0.0010649127652868629,
 0.00783482939004898,
 0.009163793176412582,
 0.009733172133564949,
 -0.005127969663590193,
 0.03400684893131256,
 0.02198803797364235,
 0.050390005111694336,
 0.02808024361729622,
 0.015285376459360123,
 0.021765628829598427,
 0.025766877457499504,
 -0.008333742618560791,
 0.02856491133570671,
 0.07146742194890976,
 0.005540117621421814,
 0.010014980100095272,
 0.009792249649763107,
 0.01813478022813797,
 0.0074698952957987785,
 -0.021789686754345894,
 -0.007367144338786602,
 -0.031819771975278854,
 0.0020056571811437607,
 0.032727036625146866,
 0.06542474776506424,
 -0.030975336208939552,
 -0.0030810381285846233,
 0.019844235852360725,
 0.03537256270647049,
 -0.03580789640545845,
 -0.013723384588956833,
 -0.03736705332994461,
 0.008333458565175533,
 -0.009105028584599495,
 0.0020263297483325005,
 0.005605634301900864,
 0.004272097256034613,
 0.017805419862270355,
 -0.0007859675097279251,
 -0.020235475152730942,
 -0.03698418661952019,
 -0.04412400722503662,
 -0.06539688259363174,
 -0.07784739136695862,
 0.015640178695321083,
 -0.03513391315937042,
 -0.04089637100696564,
 0.024822315201163292,
 -0.054893858730793,
 0.027757495641708374,
 -0.05154957249760628,
 -0.014729111455380917,
 0.00029094485216774046,
 -0.03603816777467728,
 -8.18261833046563e-05,
 0.03678309544920921,
 0.004251448903232813,
 -0.03532520309090614,
 0.06657275557518005,
 -0.02187039516866207,
 0.038515303283929825,
 -0.011465057730674744,
 -0.03181057795882225,
 0.008882762864232063,
 -0.017758158966898918,
 0.0296646635979414,
 -0.039295878261327744,
 -0.03205781430006027,
 0.005515980068594217,
 -0.0246091578155756,
 -0.03181379660964012,
 0.006074793636798859,
 -0.024217383936047554,
 -0.003200853243470192,
 -0.010659128427505493,
 -0.0501115620136261,
 0.06773620843887329,
 0.024156950414180756,
 -0.0027802481781691313,
 -0.024271361529827118,
 0.030685408040881157,
 -0.021330010145902634,
 0.05106056481599808,
 0.011207511648535728,
 0.029119469225406647,
 -0.028969937935471535,
 0.06882278621196747,
 0.06591043621301651,
 0.022287337109446526,
 0.00544134434312582,
 -0.021012986078858376,
 -0.021588772535324097,
 -0.01572769321501255,
 -0.021106665953993797,
 -0.047401152551174164,
 0.0020412891171872616,
 0.029096605256199837,
 0.04711020737886429,
 -0.08026797324419022,
 0.004596703685820103,
 -0.029690947383642197,
 -0.0830129012465477,
 -0.022455083206295967,
 0.01518446858972311,
 0.022777769714593887,
 0.024194911122322083,
 0.035336460918188095,
 -0.03890795633196831,
 -0.0042971051298081875,
 0.018689144402742386,
 0.02769342064857483,
 0.03272084891796112,
 -0.026080399751663208,
 0.026666685938835144,
 0.04261363670229912,
 0.017322635278105736,
 0.060056474059820175,
 0.009438441134989262,
 -0.03966715559363365,
 0.007296594325453043,
 0.004974912852048874,
 -0.002986499574035406,
 -0.012253088876605034,
 0.029187466949224472,
 0.002135867951437831,
 -0.01795279234647751,
 0.013051565736532211,
 -0.045906390994787216,
 0.02405499294400215,
 0.037579409778118134,
 -0.02621796354651451,
 0.023367077112197876,
 5.58491847186815e-05,
 0.021796418353915215,
 -0.05315621569752693,
 0.017994271591305733,
 -0.06199442967772484,
 -0.0027874878142029047,
 0.015318142250180244,
 0.03474421054124832,
 -0.11193598806858063,
 0.03516686335206032,
 -0.04255971312522888,
 -0.02650531381368637,
 0.01862005889415741,
 0.009200730361044407,
 -0.07185118645429611,
 0.03059990704059601,
 -0.0016198210651054978,
 0.03595553711056709,
 -0.07001876085996628,
 -0.06352341920137405,
 0.04351763054728508,
 0.003887888742610812,
 0.05351259931921959,
 0.04074900597333908,
 0.012900169938802719,
 0.0177816990762949,
 -0.045789685100317,
 -0.01753828674554825,
 -0.027182690799236298,
 0.013318098150193691,
 0.025634899735450745,
 -0.015200132504105568,
 -0.0013679665280506015,
 -0.051413148641586304,
 -0.025739355012774467,
 0.017916154116392136,
 0.029474249109625816,
 0.02795925922691822,
 -0.0028397163841873407,
 0.03161157667636871,
 0.01983463764190674,
 0.035522978752851486,
 0.011437686160206795,
 -0.03400123119354248,
 -0.0021711564622819424,
 -0.010479516349732876,
 0.04442381113767624,
 0.030675362795591354,
 0.0005590865621343255,
 -0.02208654209971428,
 -0.007465681526809931,
 -0.015356792137026787,
 0.0015407762257382274,
 -0.01657378114759922,
 0.04110239818692207,
 -0.016929201781749725,
 -0.00967256911098957,
 0.0024408006574958563,
 0.03434586152434349,
 0.008883003145456314,
 -0.020376086235046387,
 -0.059341948479413986,
 0.06007780134677887,
 0.054932303726673126,
 -0.03154676780104637,
 0.0056971157900989056,
 -0.026268234476447105,
 0.013917413540184498,
 -0.02577359229326248,
 -0.008021244779229164,
 -0.027436789125204086,
 0.007119906600564718,
 -0.004063187167048454,
 -0.024792391806840897,
 0.028239566832780838,
 -0.009047133848071098,
 -0.005261626094579697,
 0.01010336633771658,
 -0.05530192330479622,
 0.0029422948136925697,
 0.01558788400143385,
 0.0068842340260744095,
 0.03690202906727791,
 5.0252921937499195e-05,
 -0.0156015083193779,
 0.012676340527832508,
 0.04981425777077675,
 -0.0016047160606831312,
 -0.03830665349960327,
 0.0236403439193964,
 -0.016952354460954666,
 0.02818930149078369,
 -0.03854847699403763,
 -0.0235973559319973,
 -0.007596360519528389,
 0.030090687796473503,
 -0.00722885224968195,
 0.008900463581085205,
 -0.0021420540288090706,
 -0.017765270546078682,
 0.0002954526571556926,
 -0.014375057071447372,
 -0.004595991689711809,
 -0.047032680362463,
 0.04690604284405708,
 -0.0018815380753949285,
 -0.040258314460515976,
 0.014985802583396435,
 0.02522895485162735,
 0.029802469536662102,
 0.0035946101415902376,
 0.006832001265138388,
 -0.014131102710962296,
 0.01735053025186062,
 -0.027764014899730682,
 0.0038725181948393583,
 0.012292505241930485,
 0.003024299396201968,
 0.0032313535921275616,
 -0.02684190683066845,
 0.009967873804271221,
 -0.007973222993314266,
 -0.01151012908667326,
 -0.026066837832331657,
 -0.03863183781504631,
 -0.06024160236120224,
 -0.029045822098851204,
 -0.020157145336270332,
 -0.020394472405314445,
 0.03530413284897804,
 -0.010638784617185593,
 0.025497427210211754,
 -0.02296312525868416,
 -0.03317964822053909,
 0.006943101529031992,
 -0.03612112998962402,
 0.006666580215096474,
 0.05156863108277321,
 0.011167079210281372,
 0.04945319890975952,
 0.010274212807416916,
 -0.03193436563014984,
 -0.01961600035429001,
 -0.016326092183589935,
 0.02726481296122074,
 -0.02375342696905136,
 0.011796308681368828,
 0.013125889003276825,
 0.013756167143583298,
 -0.005421881563961506,
 0.0037235277704894543,
 -0.014183414168655872,
 0.0194459967315197,
 0.04434884712100029,
 -0.005938616581261158,
 -0.01749388501048088,
 -0.02801104076206684,
 -0.0435580313205719,
 0.029509982094168663,
 -0.0068445815704762936,
 -0.055413197726011276,
 -0.046169012784957886,
 0.037533558905124664,
 -0.02985156513750553,
 0.032677728682756424,
 0.047706570476293564,
 0.0004037517646793276,
 -0.020306898280978203,
 -0.07041200995445251,
 0.020613471046090126,
 -0.034545086324214935,
 -0.023709142580628395,
 -0.05635387450456619,
 0.014217454940080643,
 0.041658915579319,
 0.026940686628222466,
 0.04310588911175728,
 -0.021970536559820175,
 -0.050618793815374374,
 -0.041135016828775406,
 -0.006624368019402027,
 -0.0041145156137645245,
 -0.011664170771837234,
 -0.033444080501794815,
 0.029706068336963654,
 -0.01180525217205286,
 0.05516761168837547,
 -0.02353043667972088,
 -0.009703520685434341,
 0.011422152630984783,
 0.010469202883541584,
 0.04734286293387413,
 0.03569510579109192,
 0.005114767700433731,
 -0.035679083317518234,
 0.009219387546181679,
 -0.019716626033186913,
 0.03093140758574009,
 0.0311796423047781,
 -0.046491920948028564,
 0.016799841076135635,
 -0.05333125963807106,
 -0.009667942300438881,
 -0.023578334599733353,
 -0.005045654717832804,
 -0.0009962344774976373,
 0.010056201368570328,
 0.0144489835947752,
 -0.059230223298072815,
 -0.0031147769186645746,
 -0.04504963010549545,
 0.025345666334033012,
 0.008205506019294262,
 -0.005579902790486813,
 -0.042971327900886536,
 -0.03002128005027771,
 -0.05181368812918663,
 -0.07729730010032654,
 0.03943277522921562,
 0.0014365983661264181,
 -0.05149413272738457,
 -0.02100086398422718,
 0.024355575442314148,
 0.02292616479098797,
 -0.012116472236812115,
 0.02563205175101757,
 0.0807608887553215,
 0.02635292522609234,
 -0.03644280135631561,
 -0.016348104923963547,
 0.0092257559299469,
 -0.005261685699224472,
 -0.008306339383125305,
 -0.026826705783605576,
 -0.0008025267161428928,
 -0.026249554008245468,
 -0.0331115759909153,
 -0.04128757864236832,
 -0.028572488576173782,
 -0.010770966298878193,
 0.011588123627007008,
 0.07168176025152206,
 -0.06010763719677925,
 0.03145290166139603,
 0.00918915867805481,
 -0.036841075867414474,
 -0.026724601164460182,
 0.012200337834656239,
 0.025396475568413734,
 -0.040598973631858826,
 0.0011911364272236824,
 -0.0016462815692648292,
 0.019419092684984207,
 0.017687244340777397,
 -0.01582794450223446,
 -0.04921026527881622,
 -0.010025298222899437,
 0.046607449650764465,
 -0.007421738933771849,
 -0.0213765949010849,
 0.02028408832848072,
 0.041274771094322205,
 -0.05400998517870903,
 0.01073519978672266,
 -0.01617174781858921,
 -0.01888834312558174,
 0.010098762810230255,
 -0.029298266395926476,
 0.02078145369887352,
 0.021030573174357414,
 -0.0370001494884491,
 0.045770417898893356,
 -0.011767115443944931,
 0.009456757456064224,
 -0.0013800564920529723,
 0.0397271104156971,
 -0.01751800626516342,
 -0.02722250297665596,
 0.028272395953536034,
 0.03968773037195206,
 0.0033481197897344828,
 0.011585096828639507,
 0.009806848131120205,
 0.015724651515483856,
 -0.0016522088553756475,
 0.011843915097415447,
 0.04632719233632088,
 0.012666601687669754,
 -0.025124279782176018,
 0.033527761697769165,
 0.007063662633299828,
 0.07679849117994308,
 -0.03562391549348831,
 0.046927280724048615,
 0.04188156500458717,
 -0.02766583114862442,
 -0.03962086886167526,
 0.013063857331871986,
 0.04388238862156868,
 0.011234243400394917,
 0.0384150855243206,
 -0.054241813719272614,
 -0.007905212230980396,
 0.06585820764303207,
 0.0006462379824370146,
 -0.004550304729491472,
 -0.03526097908616066,
 -0.01973455213010311,
 -0.0779256671667099,
 0.022123126313090324,
 -0.012708190828561783,
 0.013345737010240555,
 -0.007106291130185127,
 -0.0012135981814935803,
 0.01400315947830677,
 -0.006673042196780443,
 -0.010725749656558037,
 0.03729137405753136,
 -0.015673743560910225,
 0.051183249801397324,
 -0.020731942728161812,
 0.024480337277054787,
 -0.0401487872004509,
 -0.019218377768993378,
 0.00033992069074884057,
 -0.006101594772189856,
 0.0045214262790977955,
 -7.450111752405064e-06,
 0.019603809341788292,
 0.030058613047003746,
 -0.03351679816842079,
 0.005014320835471153,
 0.025537336245179176,
 0.009832576848566532,
 0.00287995976395905,
 -0.014694261364638805,
 -0.01948501355946064,
 0.021357713267207146,
 -0.03012068197131157,
 -0.0032415890600532293,
 -0.003474799683317542,
 -0.03298940137028694,
 -0.04734310880303383,
 0.017778798937797546,
 -0.07165005803108215,
 -0.03310777619481087,
 -0.0043046423234045506,
 0.02928030863404274,
 0.05274830386042595,
 0.013935779221355915,
 -0.030676286667585373,
 0.0040040998719632626,
 -0.02212236076593399,
 -0.03516995534300804,
 0.017980417236685753,
 -0.032826367765665054,
 0.009842553175985813,
 0.008278190158307552,
 0.04544486477971077,
 0.0777307003736496,
 0.01296254526823759,
 0.029987772926688194,
 -0.028262704610824585,
 0.009998904541134834,
 0.0327678881585598,
 -0.009070208296179771,
 0.002738434821367264,
 -0.03270037844777107,
 -0.00031733131618238986,
 0.002165011130273342,
 -0.010316109284758568,
 -0.006685889791697264,
 -0.018151145428419113,
 -0.01755661889910698,
 0.01235936302691698,
 0.008702089078724384,
 0.010564854368567467,
 0.038292478770017624,
 0.03140409663319588,
 0.051776181906461716,
 0.0005989411729387939,
 -0.05189528688788414,
 0.021822068840265274,
 -0.05220385268330574,
 -0.027351129800081253,
 -0.044767189770936966,
 -0.048987045884132385,
 -0.014465383253991604,
 0.04118026793003082,
 -0.0077504366636276245,
 0.01705912873148918,
 -0.0035669300705194473,
 -0.014973555691540241,
 0.00571567052975297,
 0.042476531118154526,
 0.008216328918933868,
 0.004580141976475716,
 0.009374817833304405,
 -0.040978122502565384,
 -0.004634896293282509,
 -0.03793330118060112,
 0.007277649361640215,
 -0.012144249863922596,
 0.019600795581936836,
 -0.046763163059949875,
 -0.0327848345041275,
 0.012845456600189209,
 0.0029605901800096035,
 -0.02306547574698925,
 0.004379724618047476,
 -0.020817341282963753,
 -0.008798201568424702,
 0.0034820057917386293,
 -0.018539823591709137,
 0.0011653800029307604,
 0.007556346710771322,
 -0.010651864111423492,
 -0.0020534577779471874,
 0.006361751817166805,
 0.007174920290708542,
 0.004852599930018187,
 0.03366103395819664,
 0.005266458261758089,
 -0.003673205152153969,
 -0.009889010339975357,
 0.051384102553129196,
 -0.016463657841086388,
 0.031067820265889168,
 0.02171177975833416,
 0.023806313052773476,
 0.028306346386671066,
 0.008995427750051022,
 -0.020931193605065346,
 0.00826928298920393,
 0.04434001073241234,
 0.035888999700546265,
 -0.023181399330496788,
 -0.020392868667840958,
 0.03996346518397331,
 0.028400707989931107,
 -0.027467351406812668,
 -0.004822054412215948,
 0.04876341670751572,
 -0.0188603475689888,
 0.006356247700750828,
 0.020519472658634186,
 -0.04412969574332237,
 0.005492552183568478,
 0.023976022377610207,
 -0.018401550129055977,
 0.002328100148588419,
 -0.01614426262676716,
 -0.05339481309056282,
 -0.011189770884811878,
 -0.01481554377824068,
 0.02909970097243786,
 -0.0066644358448684216,
 -0.07552230358123779,
 -0.033441755920648575,
 0.031213438138365746,
 -0.0022525328677147627,
 0.02239937335252762,
 0.005479036830365658,
 -0.0022542572114616632,
 0.06569208204746246,
 0.006163871381431818,
 0.030064716935157776,
 0.044599756598472595,
 -0.036252714693546295,
 0.014662697911262512,
 -0.014066887088119984,
 -0.020240386947989464,
 -0.005132876802235842,
 -0.007203487679362297,
 0.00031675875652581453,
 -0.037291768938302994,
 -0.01317592803388834,
 0.02503199316561222,
 0.0004417097952682525,
 -0.013611194677650928,
 0.04001652076840401,
 -0.0188665222376585,
 -0.010018577799201012,
 -0.03941350430250168,
 0.024801788851618767,
 -0.05455491691827774,
 0.01132796611636877,
 0.06886307895183563,
 -0.04869642108678818,
 -0.02394901216030121,
 0.0352632962167263,
 0.010679427534341812,
 0.008192816749215126,
 0.024219971150159836,
 0.06820628046989441,
 0.04121825471520424,
 0.07895822823047638,
 0.05513179302215576,
 -0.0013215621002018452,
 0.004935598466545343,
 0.016455048695206642,
 -0.011337478645145893,

#### Create Qdrant collection

In [23]:
qdrant_client = QdrantClient(url="http://localhost:6333")

/home/nurda/ai-engineering/.venv/lib/python3.12/site-packages/qdrant_client/qdrant_remote.py:288: UserWarning: Failed to obtain server version. Unable to check client-server compatibility. Set check_compatibility=False to skip version check.
  show_warning(

In [41]:
qdrant_client.create_collection(
    collection_name="Amazon_items_collection1",
    vectors_config=VectorParams(
        size=768,
        distance=Distance.COSINE
    )
)

True

#### Embed data

In [27]:
pointstruct = PointStruct(
    id=0,
    vector=get_embedding("This is a sample description for embedding."),
    payload={
        "text": "This is a sample description for embedding.",
        "model": "text-embedding-3-small",
    }
)

In [28]:
pointstruct

PointStruct(id=0, vector=[-0.00948325078934431, 0.012058141641318798, 0.027258556336164474, -0.05333848297595978, -0.00197103270329535, -0.01828557625412941, -0.026689395308494568, -0.020734688267111778, 0.027556661516427994, 0.01653590053319931, 0.03787371143698692, -0.002093489747494459, 0.03336760401725769, 0.008175315335392952, -0.015481525100767612, 0.003441209439188242, -0.019416728988289833, -0.05459068715572357, -0.03769243136048317, -0.04583422467112541, -0.04796198010444641, 0.020276710391044617, -0.0745227262377739, -0.017317868769168854, -0.015847085043787956, 0.03982369229197502, 0.039216477423906326, 0.03783240541815758, 0.06001000106334686, -0.009964903816580772, 0.002223898656666279, 0.03785277530550957, 0.0012547960504889488, -0.05744506046175957, -0.006924338173121214, -0.006462203338742256, 0.04315252602100372, -0.048255693167448044, -0.017380185425281525, -0.04144918546080589, 0.011150099337100983, 0.002850027522072196, 0.0482356883585453, -0.04788336530327797, -0.05741036683320999, 0.0005746546084992588, 0.03210902586579323, -0.014518295414745808, 0.013209976255893707, -0.03972760587930679, 0.012333331629633904, 0.00018908618949353695, -0.0037038717418909073, -0.026760201901197433, 0.024434853345155716, -0.02053077146410942, -0.01771901361644268, -0.019388357177376747, -0.024289753288030624, 0.03219548240303993, 0.031001731753349304, 0.006292041856795549, 0.04318604990839958, -0.07863274216651917, -0.012635793536901474, -0.0023903357796370983, -0.03957638144493103, 0.017494220286607742, -0.027335241436958313, -0.015464157797396183, -0.03535633534193039, -0.01219868939369917, -0.018207816407084465, -0.03162885829806328, -0.02320607751607895, -0.01287612784653902, -0.010895436629652977, -0.004307047929614782, -0.015212482772767544, 0.035079225897789, 0.018904181197285652, 0.028758510947227478, 0.0027208656538277864, 0.0015358629170805216, -0.04243661090731621, -0.03997265547513962, 0.008622960187494755, 0.01416836678981781, 0.022410336881875992, -0.02856268920004368, -0.016190633177757263, 0.05974656343460083, -0.016070101410150528, 0.03870896250009537, -0.015582592226564884, 0.004434223286807537, -0.02101636864244938, 0.036060966551303864, -0.00108792120590806, 0.03382252901792526, 0.059683747589588165, 0.05600687861442566, 0.00902065820991993, 0.05620715394616127, -0.06347155570983887, 0.04076037555932999, 0.015918007120490074, -0.010999005287885666, -0.04575864225625992, -0.018091591075062752, 0.012281165458261967, -0.00994543731212616, 0.015495635569095612, -0.023462790995836258, -0.04132119566202164, 0.01185164600610733, 0.0027273232117295265, 0.018645061179995537, 0.0029385352972894907, 0.008828774094581604, -0.05182182043790817, 0.018374362960457802, -0.023188484832644463, -0.064976267516613, -0.002197731053456664, 0.002361263381317258, 0.0014176280237734318, 0.0394088551402092, -0.043541599065065384, 0.0123300114646554, 0.019280394539237022, 0.007367542013525963, 0.03494850546121597, 0.0343194380402565, -0.043453313410282135, -0.0035958504304289818, -0.017188964411616325, 0.017652306705713272, 0.01973084919154644, 0.004233216401189566, 0.00012792884081136435, -0.0033467700704932213, -0.04356851056218147, 0.07676228135824203, -0.0023094560019671917, 0.01661752723157406, -0.0066398149356245995, -0.03521810099482536, -0.03237039968371391, 0.05275474861264229, 0.008593091741204262, -0.019066350534558296, 0.02150386944413185, 0.006900661159306765, -0.031129589304327965, -0.007405301555991173, -0.008619368076324463, 0.003927921876311302, -0.02416241355240345, -0.014501923695206642, 0.022911371663212776, 0.008903970941901207, -0.019886061549186707, 0.07212807983160019, -0.04554568603634834, 0.017394395545125008, -0.05779493227601051, -0.003800417063757777, -0.04030710458755493, -0.021645009517669678, -0.001952784019522369, 0.02605360560119152, 0.02630717121064663, -0.03206295520067215, -0.015708062797784805, 0.01673293299973011, 0.013827499933540821, 0.015243100933730602, 0.06961426138877869, -0.0006085060886107385, 0.000607311783824116, -0.031115293502807617, 0.025553695857524872, 0.019456490874290466, -0.03440721705555916, -0.003591081127524376, -0.027301223948597908, 0.011538781225681305, -0.02402608096599579, 0.02000110223889351, 0.01272676419466734, 0.04620828852057457, -0.024081602692604065, 0.02662939950823784, 0.0018956545973196626, 0.01716887392103672, -0.030780773609876633, 0.002343713538721204, -0.02850966341793537, -0.07027877867221832, -0.0322122797369957, -0.008456483483314514, -0.026099354028701782, -0.0015656932955607772, -0.021442029625177383, -0.0034903299529105425, -0.007487535942345858, 0.07180003821849823, -0.03392038866877556, 0.014345556497573853, 0.024131428450345993, -0.01775391213595867, -0.002766686026006937, -0.010109427385032177, 0.05021846666932106, -0.02335124835371971, -0.008128576911985874, 0.04314495995640755, 0.003221027087420225, 0.006394787225872278, -0.008992751128971577, 0.029497897252440453, 0.015318159945309162, 0.009907458908855915, -0.014666746370494366, -0.016365036368370056, -0.007258111145347357, 0.04916340485215187, -0.0010649127652868629, 0.00783482939004898, 0.009163793176412582, 0.009733172133564949, -0.005127969663590193, 0.03400684893131256, 0.02198803797364235, 0.050390005111694336, 0.02808024361729622, 0.015285376459360123, 0.021765628829598427, 0.025766877457499504, -0.008333742618560791, 0.02856491133570671, 0.07146742194890976, 0.005540117621421814, 0.010014980100095272, 0.009792249649763107, 0.01813478022813797, 0.0074698952957987785, -0.021789686754345894, -0.007367144338786602, -0.031819771975278854, 0.0020056571811437607, 0.032727036625146866, 0.06542474776506424, -0.030975336208939552, -0.0030810381285846233, 0.019844235852360725, 0.03537256270647049, -0.03580789640545845, -0.013723384588956833, -0.03736705332994461, 0.008333458565175533, -0.009105028584599495, 0.0020263297483325005, 0.005605634301900864, 0.004272097256034613, 0.017805419862270355, -0.0007859675097279251, -0.020235475152730942, -0.03698418661952019, -0.04412400722503662, -0.06539688259363174, -0.07784739136695862, 0.015640178695321083, -0.03513391315937042, -0.04089637100696564, 0.024822315201163292, -0.054893858730793, 0.027757495641708374, -0.05154957249760628, -0.014729111455380917, 0.00029094485216774046, -0.03603816777467728, -8.18261833046563e-05, 0.03678309544920921, 0.004251448903232813, -0.03532520309090614, 0.06657275557518005, -0.02187039516866207, 0.038515303283929825, -0.011465057730674744, -0.03181057795882225, 0.008882762864232063, -0.017758158966898918, 0.0296646635979414, -0.039295878261327744, -0.03205781430006027, 0.005515980068594217, -0.0246091578155756, -0.03181379660964012, 0.006074793636798859, -0.024217383936047554, -0.003200853243470192, -0.010659128427505493, -0.0501115620136261, 0.06773620843887329, 0.024156950414180756, -0.0027802481781691313, -0.024271361529827118, 0.030685408040881157, -0.021330010145902634, 0.05106056481599808, 0.011207511648535728, 0.029119469225406647, -0.028969937935471535, 0.06882278621196747, 0.06591043621301651, 0.022287337109446526, 0.00544134434312582, -0.021012986078858376, -0.021588772535324097, -0.01572769321501255, -0.021106665953993797, -0.047401152551174164, 0.0020412891171872616, 0.029096605256199837, 0.04711020737886429, -0.08026797324419022, 0.004596703685820103, -0.029690947383642197, -0.0830129012465477, -0.022455083206295967, 0.01518446858972311, 0.022777769714593887, 0.024194911122322083, 0.035336460918188095, -0.03890795633196831, -0.0042971051298081875, 0.018689144402742386, 0.02769342064857483, 0.03272084891796112, -0.026080399751663208, 0.026666685938835144, 0.04261363670229912, 0.017322635278105736, 0.060056474059820175, 0.009438441134989262, -0.03966715559363365, 0.007296594325453043, 0.004974912852048874, -0.002986499574035406, -0.012253088876605034, 0.029187466949224472, 0.002135867951437831, -0.01795279234647751, 0.013051565736532211, -0.045906390994787216, 0.02405499294400215, 0.037579409778118134, -0.02621796354651451, 0.023367077112197876, 5.58491847186815e-05, 0.021796418353915215, -0.05315621569752693, 0.017994271591305733, -0.06199442967772484, -0.0027874878142029047, 0.015318142250180244, 0.03474421054124832, -0.11193598806858063, 0.03516686335206032, -0.04255971312522888, -0.02650531381368637, 0.01862005889415741, 0.009200730361044407, -0.07185118645429611, 0.03059990704059601, -0.0016198210651054978, 0.03595553711056709, -0.07001876085996628, -0.06352341920137405, 0.04351763054728508, 0.003887888742610812, 0.05351259931921959, 0.04074900597333908, 0.012900169938802719, 0.0177816990762949, -0.045789685100317, -0.01753828674554825, -0.027182690799236298, 0.013318098150193691, 0.025634899735450745, -0.015200132504105568, -0.0013679665280506015, -0.051413148641586304, -0.025739355012774467, 0.017916154116392136, 0.029474249109625816, 0.02795925922691822, -0.0028397163841873407, 0.03161157667636871, 0.01983463764190674, 0.035522978752851486, 0.011437686160206795, -0.03400123119354248, -0.0021711564622819424, -0.010479516349732876, 0.04442381113767624, 0.030675362795591354, 0.0005590865621343255, -0.02208654209971428, -0.007465681526809931, -0.015356792137026787, 0.0015407762257382274, -0.01657378114759922, 0.04110239818692207, -0.016929201781749725, -0.00967256911098957, 0.0024408006574958563, 0.03434586152434349, 0.008883003145456314, -0.020376086235046387, -0.059341948479413986, 0.06007780134677887, 0.054932303726673126, -0.03154676780104637, 0.0056971157900989056, -0.026268234476447105, 0.013917413540184498, -0.02577359229326248, -0.008021244779229164, -0.027436789125204086, 0.007119906600564718, -0.004063187167048454, -0.024792391806840897, 0.028239566832780838, -0.009047133848071098, -0.005261626094579697, 0.01010336633771658, -0.05530192330479622, 0.0029422948136925697, 0.01558788400143385, 0.0068842340260744095, 0.03690202906727791, 5.0252921937499195e-05, -0.0156015083193779, 0.012676340527832508, 0.04981425777077675, -0.0016047160606831312, -0.03830665349960327, 0.0236403439193964, -0.016952354460954666, 0.02818930149078369, -0.03854847699403763, -0.0235973559319973, -0.007596360519528389, 0.030090687796473503, -0.00722885224968195, 0.008900463581085205, -0.0021420540288090706, -0.017765270546078682, 0.0002954526571556926, -0.014375057071447372, -0.004595991689711809, -0.047032680362463, 0.04690604284405708, -0.0018815380753949285, -0.040258314460515976, 0.014985802583396435, 0.02522895485162735, 0.029802469536662102, 0.0035946101415902376, 0.006832001265138388, -0.014131102710962296, 0.01735053025186062, -0.027764014899730682, 0.0038725181948393583, 0.012292505241930485, 0.003024299396201968, 0.0032313535921275616, -0.02684190683066845, 0.009967873804271221, -0.007973222993314266, -0.01151012908667326, -0.026066837832331657, -0.03863183781504631, -0.06024160236120224, -0.029045822098851204, -0.020157145336270332, -0.020394472405314445, 0.03530413284897804, -0.010638784617185593, 0.025497427210211754, -0.02296312525868416, -0.03317964822053909, 0.006943101529031992, -0.03612112998962402, 0.006666580215096474, 0.05156863108277321, 0.011167079210281372, 0.04945319890975952, 0.010274212807416916, -0.03193436563014984, -0.01961600035429001, -0.016326092183589935, 0.02726481296122074, -0.02375342696905136, 0.011796308681368828, 0.013125889003276825, 0.013756167143583298, -0.005421881563961506, 0.0037235277704894543, -0.014183414168655872, 0.0194459967315197, 0.04434884712100029, -0.005938616581261158, -0.01749388501048088, -0.02801104076206684, -0.0435580313205719, 0.029509982094168663, -0.0068445815704762936, -0.055413197726011276, -0.046169012784957886, 0.037533558905124664, -0.02985156513750553, 0.032677728682756424, 0.047706570476293564, 0.0004037517646793276, -0.020306898280978203, -0.07041200995445251, 0.020613471046090126, -0.034545086324214935, -0.023709142580628395, -0.05635387450456619, 0.014217454940080643, 0.041658915579319, 0.026940686628222466, 0.04310588911175728, -0.021970536559820175, -0.050618793815374374, -0.041135016828775406, -0.006624368019402027, -0.0041145156137645245, -0.011664170771837234, -0.033444080501794815, 0.029706068336963654, -0.01180525217205286, 0.05516761168837547, -0.02353043667972088, -0.009703520685434341, 0.011422152630984783, 0.010469202883541584, 0.04734286293387413, 0.03569510579109192, 0.005114767700433731, -0.035679083317518234, 0.009219387546181679, -0.019716626033186913, 0.03093140758574009, 0.0311796423047781, -0.046491920948028564, 0.016799841076135635, -0.05333125963807106, -0.009667942300438881, -0.023578334599733353, -0.005045654717832804, -0.0009962344774976373, 0.010056201368570328, 0.0144489835947752, -0.059230223298072815, -0.0031147769186645746, -0.04504963010549545, 0.025345666334033012, 0.008205506019294262, -0.005579902790486813, -0.042971327900886536, -0.03002128005027771, -0.05181368812918663, -0.07729730010032654, 0.03943277522921562, 0.0014365983661264181, -0.05149413272738457, -0.02100086398422718, 0.024355575442314148, 0.02292616479098797, -0.012116472236812115, 0.02563205175101757, 0.0807608887553215, 0.02635292522609234, -0.03644280135631561, -0.016348104923963547, 0.0092257559299469, -0.005261685699224472, -0.008306339383125305, -0.026826705783605576, -0.0008025267161428928, -0.026249554008245468, -0.0331115759909153, -0.04128757864236832, -0.028572488576173782, -0.010770966298878193, 0.011588123627007008, 0.07168176025152206, -0.06010763719677925, 0.03145290166139603, 0.00918915867805481, -0.036841075867414474, -0.026724601164460182, 0.012200337834656239, 0.025396475568413734, -0.040598973631858826, 0.0011911364272236824, -0.0016462815692648292, 0.019419092684984207, 0.017687244340777397, -0.01582794450223446, -0.04921026527881622, -0.010025298222899437, 0.046607449650764465, -0.007421738933771849, -0.0213765949010849, 0.02028408832848072, 0.041274771094322205, -0.05400998517870903, 0.01073519978672266, -0.01617174781858921, -0.01888834312558174, 0.010098762810230255, -0.029298266395926476, 0.02078145369887352, 0.021030573174357414, -0.0370001494884491, 0.045770417898893356, -0.011767115443944931, 0.009456757456064224, -0.0013800564920529723, 0.0397271104156971, -0.01751800626516342, -0.02722250297665596, 0.028272395953536034, 0.03968773037195206, 0.0033481197897344828, 0.011585096828639507, 0.009806848131120205, 0.015724651515483856, -0.0016522088553756475, 0.011843915097415447, 0.04632719233632088, 0.012666601687669754, -0.025124279782176018, 0.033527761697769165, 0.007063662633299828, 0.07679849117994308, -0.03562391549348831, 0.046927280724048615, 0.04188156500458717, -0.02766583114862442, -0.03962086886167526, 0.013063857331871986, 0.04388238862156868, 0.011234243400394917, 0.0384150855243206, -0.054241813719272614, -0.007905212230980396, 0.06585820764303207, 0.0006462379824370146, -0.004550304729491472, -0.03526097908616066, -0.01973455213010311, -0.0779256671667099, 0.022123126313090324, -0.012708190828561783, 0.013345737010240555, -0.007106291130185127, -0.0012135981814935803, 0.01400315947830677, -0.006673042196780443, -0.010725749656558037, 0.03729137405753136, -0.015673743560910225, 0.051183249801397324, -0.020731942728161812, 0.024480337277054787, -0.0401487872004509, -0.019218377768993378, 0.00033992069074884057, -0.006101594772189856, 0.0045214262790977955, -7.450111752405064e-06, 0.019603809341788292, 0.030058613047003746, -0.03351679816842079, 0.005014320835471153, 0.025537336245179176, 0.009832576848566532, 0.00287995976395905, -0.014694261364638805, -0.01948501355946064, 0.021357713267207146, -0.03012068197131157, -0.0032415890600532293, -0.003474799683317542, -0.03298940137028694, -0.04734310880303383, 0.017778798937797546, -0.07165005803108215, -0.03310777619481087, -0.0043046423234045506, 0.02928030863404274, 0.05274830386042595, 0.013935779221355915, -0.030676286667585373, 0.0040040998719632626, -0.02212236076593399, -0.03516995534300804, 0.017980417236685753, -0.032826367765665054, 0.009842553175985813, 0.008278190158307552, 0.04544486477971077, 0.0777307003736496, 0.01296254526823759, 0.029987772926688194, -0.028262704610824585, 0.009998904541134834, 0.0327678881585598, -0.009070208296179771, 0.002738434821367264, -0.03270037844777107, -0.00031733131618238986, 0.002165011130273342, -0.010316109284758568, -0.006685889791697264, -0.018151145428419113, -0.01755661889910698, 0.01235936302691698, 0.008702089078724384, 0.010564854368567467, 0.038292478770017624, 0.03140409663319588, 0.051776181906461716, 0.0005989411729387939, -0.05189528688788414, 0.021822068840265274, -0.05220385268330574, -0.027351129800081253, -0.044767189770936966, -0.048987045884132385, -0.014465383253991604, 0.04118026793003082, -0.0077504366636276245, 0.01705912873148918, -0.0035669300705194473, -0.014973555691540241, 0.00571567052975297, 0.042476531118154526, 0.008216328918933868, 0.004580141976475716, 0.009374817833304405, -0.040978122502565384, -0.004634896293282509, -0.03793330118060112, 0.007277649361640215, -0.012144249863922596, 0.019600795581936836, -0.046763163059949875, -0.0327848345041275, 0.012845456600189209, 0.0029605901800096035, -0.02306547574698925, 0.004379724618047476, -0.020817341282963753, -0.008798201568424702, 0.0034820057917386293, -0.018539823591709137, 0.0011653800029307604, 0.007556346710771322, -0.010651864111423492, -0.0020534577779471874, 0.006361751817166805, 0.007174920290708542, 0.004852599930018187, 0.03366103395819664, 0.005266458261758089, -0.003673205152153969, -0.009889010339975357, 0.051384102553129196, -0.016463657841086388, 0.031067820265889168, 0.02171177975833416, 0.023806313052773476, 0.028306346386671066, 0.008995427750051022, -0.020931193605065346, 0.00826928298920393, 0.04434001073241234, 0.035888999700546265, -0.023181399330496788, -0.020392868667840958, 0.03996346518397331, 0.028400707989931107, -0.027467351406812668, -0.004822054412215948, 0.04876341670751572, -0.0188603475689888, 0.006356247700750828, 0.020519472658634186, -0.04412969574332237, 0.005492552183568478, 0.023976022377610207, -0.018401550129055977, 0.002328100148588419, -0.01614426262676716, -0.05339481309056282, -0.011189770884811878, -0.01481554377824068, 0.02909970097243786, -0.0066644358448684216, -0.07552230358123779, -0.033441755920648575, 0.031213438138365746, -0.0022525328677147627, 0.02239937335252762, 0.005479036830365658, -0.0022542572114616632, 0.06569208204746246, 0.006163871381431818, 0.030064716935157776, 0.044599756598472595, -0.036252714693546295, 0.014662697911262512, -0.014066887088119984, -0.020240386947989464, -0.005132876802235842, -0.007203487679362297, 0.00031675875652581453, -0.037291768938302994, -0.01317592803388834, 0.02503199316561222, 0.0004417097952682525, -0.013611194677650928, 0.04001652076840401, -0.0188665222376585, -0.010018577799201012, -0.03941350430250168, 0.024801788851618767, -0.05455491691827774, 0.01132796611636877, 0.06886307895183563, -0.04869642108678818, -0.02394901216030121, 0.0352632962167263, 0.010679427534341812, 0.008192816749215126, 0.024219971150159836, 0.06820628046989441, 0.04121825471520424, 0.07895822823047638, 0.05513179302215576, -0.0013215621002018452, 0.004935598466545343, 0.016455048695206642, -0.011337478645145893, -0.00468219630420208, 0.023644156754016876, -0.014339282177388668, 0.02847951650619507, -0.029331712052226067, -0.033532045781612396, 0.007692927494645119, 0.005962233059108257, 0.019211946055293083, -0.053674787282943726, 0.03507939726114273, 0.022395746782422066, -0.01608317531645298, 0.005716850981116295, 0.06637056916952133, 0.016895605251193047, 0.014342858456075191, -0.010211101733148098, 0.0011036146897822618, -0.012820404022932053, 0.006811290048062801, -0.054371703416109085, 0.08500021696090698, -0.015307196415960789, -0.03169187903404236, -0.030976586043834686, -0.016676880419254303, -0.034156400710344315, -0.001474107732065022, 0.00435926578938961, 0.004910305142402649, 0.03377685695886612, 0.04829315468668938, 0.019850002601742744, 0.012383965775370598, -0.05261753499507904, -0.027712557464838028, 0.034997642040252686, 0.

#### Amazon data

In [42]:
pointstruct = []

for i, data in enumerate(data_to_embed):
    embedding = get_embedding(data["description"])
    pointstruct.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload=data
        )
    )

In [37]:
pointstruct

[PointStruct(id=0, vector=[0.013423208147287369, 0.05709562823176384, -0.17772410809993744, 0.015171516686677933, 0.1015402227640152, -0.05331674963235855, 0.03367140144109726, 0.008494429290294647, -0.01655389927327633, -0.027801621705293655, -0.01265675574541092, 0.048786960542201996, 0.05174693092703819, 0.03933154046535492, -0.03218289092183113, -0.006248887162655592, -0.016131896525621414, -0.04704158008098602, 0.016664749011397362, 0.05148911103606224, -0.008599835447967052, -0.03788148611783981, -0.06307704746723175, -0.05267710983753204, 0.034267526119947433, 0.03648051247000694, 0.002132571768015623, -0.04958544299006462, -0.06469915807247162, 0.007702807430177927, 0.07936262339353561, -0.04484635591506958, -0.06843358278274536, -0.018542218953371048, -0.02708554081618786, -0.048753317445516586, -0.018149811774492264, -0.028110746294260025, -0.019198333844542503, 0.046231064945459366, 0.04992655664682388, -0.021877076476812363, 0.03551079332828522, 0.008130664937198162, 0.08716416358947754, 0.013468105345964432, 0.06332815438508987, -0.011655340902507305, 0.05301818996667862, -0.05265221744775772, -0.016603201627731323, -0.023247716948390007, 0.013970591127872467, 0.010778633877635002, 0.043290089815855026, 0.00032037642085924745, -0.06966593116521835, -0.006438992917537689, -0.01111193560063839, -0.02602146379649639, 0.05391743779182434, 0.050378698855638504, 0.005034723784774542, 0.01886346936225891, 0.05184981971979141, -0.02101784572005272, -0.0156919714063406, 0.059453025460243225, -0.030555209144949913, -0.05841635912656784, 0.05770032852888107, -0.06627529114484787, -0.004375888034701347, 0.01419068407267332, 0.0007314102258533239, -0.052880462259054184, -0.033438146114349365, -0.06791136413812637, -0.011851412244141102, 0.051872093230485916, 0.03234703093767166, -0.022862115874886513, 0.03825509548187256, -3.502286926959641e-05, 0.02900185063481331, -0.06629148870706558, -0.0033850024919956923, 0.020461028441786766, -0.0257707629352808, 0.0848124548792839, -0.018040155991911888, 0.01078761462122202, 0.041594039648771286, 0.00634522270411253, -0.025102054700255394, 0.025995826348662376, 0.0011995409149676561, 0.04425618425011635, -0.009055428206920624, -0.049296941608190536, -0.021608596667647362, 0.0007287632906809449, 0.0575692243874073, 0.009256185963749886, -0.0063585322350263596, 0.04543405398726463, 0.01336589828133583, 0.04577380418777466, -0.009205290116369724, -0.0060999770648777485, -0.014707343652844429, 0.008739739656448364, 0.04527590423822403, -0.0034377158153802156, 0.015478534623980522, -0.000914495438337326, 0.02112671174108982, 0.04057624936103821, 0.029100876301527023, 0.025230657309293747, -0.018925853073596954, 0.005534945521503687, -0.01333786454051733, 0.04119156673550606, -0.030034223571419716, 0.003392000449821353, -0.051223281770944595, -0.027037983760237694, -0.04242628067731857, -0.04264787957072258, -0.0015510442899540067, -0.03889309987425804, -0.01860971562564373, 0.013311530463397503, -0.016513224691152573, 0.07408412545919418, -0.04352875053882599, -0.04230133071541786, 0.015188151970505714, -0.01084593404084444, 0.006047876086086035, 0.05540464445948601, -0.03828135505318642, 0.01763901300728321, -0.05246835574507713, -0.029169974848628044, -0.009464873932301998, -0.010009360499680042, -0.011649074032902718, 0.0435849092900753, 0.04469795525074005, 0.007160281762480736, -0.0023383130319416523, 0.0847361832857132, 0.024342268705368042, -0.06241912394762039, 0.03346710279583931, 0.048988182097673416, 0.037879593670368195, 0.04638373479247093, 0.026740586385130882, 0.021095866337418556, -0.05782297998666763, 0.09013859927654266, -0.0508558452129364, -0.08671759068965912, 0.008637932129204273, 0.0621827207505703, 0.034980714321136475, 0.03064849227666855, -0.09914357215166092, 0.0025458643212914467, 0.027490632608532906, 0.013390262611210346, 0.005174183752387762, -0.02101190946996212, 0.012645258568227291, -0.031202804297208786, -0.05354059115052223, -0.03458665311336517, -0.024584045633673668, -0.02797103114426136, -0.01191629283130169, -0.016022877767682076, -0.04363122582435608, 0.013240893371403217, 0.07024628669023514, -0.018173497170209885, -0.02073141559958458, 0.006621157750487328, -0.017979975789785385, 0.01601707562804222, -0.028065131977200508, -0.021247515454888344, -0.07016626745462418, -0.047416262328624725, 0.03819651901721954, 0.0008703667554073036, 0.051402077078819275, -0.049211423844099045, -0.02353917807340622, 0.00590875931084156, 0.004350092727690935, -0.0039556934498250484, -0.01348233874887228, 0.011893103830516338, 0.031329259276390076, 0.052172791212797165, 0.01126856915652752, 0.049855176359415054, 0.018143560737371445, -0.06529566645622253, -0.002098574535921216, 0.022893916815519333, 0.04496133327484131, 0.0057924287393689156, 0.018954897299408913, -0.039136528968811035, -0.026831692084670067, 0.05205395817756653, 0.061941325664520264, 0.0054511758498847485, 0.016762757673859596, -0.06849432736635208, 0.014340211637318134, -0.02559516578912735, -0.034619178622961044, -0.013585297390818596, 0.010469322092831135, 0.04296752065420151, -0.0564754419028759, -0.03880006819963455, 0.031111614778637886, 0.021435607224702835, -0.012371794320642948, 0.04409494623541832, -0.032379910349845886, 0.05654783919453621, 0.004788621328771114, 0.02112877368927002, 0.03237021341919899, 0.06854467839002609, -0.022642137482762337, -0.03401083126664162, -0.04703705757856369, -0.02483680099248886, -0.016387781128287315, -0.03982292488217354, -0.01821545697748661, 0.042241550981998444, 0.012617881409823895, -0.016574552282691002, 0.045767892152071, 0.025977222248911858, 0.01185155101120472, -0.02257385291159153, -0.012947873212397099, -0.008279979228973389, -0.0084394421428442, -0.008297775872051716, -0.012506633996963501, 0.006926798261702061, 0.004822611343115568, -0.07208693772554398, -0.0021581861656159163, -0.018135735765099525, -0.010421045124530792, 0.009871282614767551, 0.004721255507320166, 0.026736361905932426, 0.048641130328178406, 0.017554957419633865, -0.011457784101366997, 0.0241698008030653, 0.015132201835513115, 0.03702820464968681, 0.06522579491138458, -0.030134856700897217, -0.00588056817650795, 0.02129850536584854, -0.03278884291648865, -0.08818373829126358, -0.003445003880187869, -0.01926949806511402, -0.04623579606413841, 6.919712177477777e-05, 0.009793742559850216, 0.02201530709862709, 0.03237171098589897, 0.05382746830582619, 0.024646203964948654, -0.004244313575327396, -0.008750651963055134, 0.015789978206157684, 0.006675070151686668, 0.026808561757206917, 0.06731678545475006, -0.002934518503025174, 0.004636541940271854, -0.004909313749521971, 0.06963440030813217, 0.03906414657831192, 0.09637939929962158, 0.0001597371738171205, -0.04683021083474159, -0.03675341606140137, 0.010685206390917301, 0.020208051428198814, -0.010829719714820385, -0.01516950223594904, -0.026609238237142563, -0.05317863076925278, -0.02133684605360031, 0.06925399601459503, -0.03550738841295242, -0.019696995615959167, 0.027219174429774284, 0.03377613425254822, 0.02133841998875141, 0.020739540457725525, 0.007908741012215614, -0.03952513635158539, -0.014100005850195885, -0.08687495440244675, -0.02577674388885498, 0.0750712901353836, 0.023286867886781693, -0.015563149936497211, 0.015917925164103508, -0.008783122524619102, -0.009739038534462452, 0.0511753149330616, 0.025313731282949448, -0.040298741310834885, -0.020943330600857735, 0.023455403745174408, 0.007611840032041073, 0.049564361572265625, 0.016031648963689804, -0.02111034095287323, 0.020172029733657837, 0.04201997071504593, 0.0008349656709469855, -0.01580626145005226, -0.01766168139874935, -0.04445647820830345, -0.04037495702505112, -0.006597951985895634, 0.01486451830714941, 0.012378606013953686, -0.012575349770486355, 0.012444766238331795, -0.021006422117352486, 0.0058315210044384, -0.003105354495346546, 0.0011031216708943248, -0.06376268714666367, 0.035214707255363464, 0.020474549382925034, -0.00997229665517807, 0.039427317678928375, 0.0672462061047554, 0.046650227159261703, 0.027580341324210167, -0.02554616704583168, 0.0025030593387782574, -0.01126785110682249, -0.00029985408764332533, -0.012631673365831375, -0.0033120685257017612, -0.006503551732748747, -0.03629396855831146, -0.016858186572790146, -0.014314328320324421, 0.014600323513150215, 0.014467673376202583, -0.08028817176818848, -0.008633404970169067, -0.043964166194200516, 0.046452946960926056, 0.0030256269965320826, -0.054684534668922424, -0.014560118317604065, 0.030183974653482437, 0.022627217695116997, -0.028060654178261757, 0.05327652767300606, -0.061287909746170044, 0.011170187965035439, 0.04851122573018074, 0.01168642845004797, -0.006212025415152311, -0.037318211048841476, -0.027291681617498398, 0.021399548277258873, -0.07621902227401733, 0.053925253450870514, -0.03627672791481018, 0.014461327344179153, 0.040158260613679886, -0.04437471181154251, -0.034144721925258636, 0.043600644916296005, 0.011242195032536983, 0.012252629734575748, 0.02227308601140976, -0.01729828305542469, -0.010760866105556488, 0.05468497425317764, 0.011596891097724438, -0.001218541874550283, 0.010233072564005852, 0.008236370980739594, -0.034854717552661896, 0.045753363519907, 0.05837295204401016, 0.036155130714178085, 0.008547212928533554, -0.018747273832559586, -0.029031092301011086, 0.045703381299972534, 0.060432929545640945, -0.015425416640937328, -0.01397168729454279, -0.006601424887776375, 0.05107136443257332, 0.03751415014266968, 0.03824831172823906, -0.0005881153047084808, 0.016130518168210983, 0.021932220086455345, 0.004369634669274092, 0.030716218054294586, 0.004923565778881311, 0.007303840946406126, 0.013441882096230984, 0.02969164401292801, 0.03830753639340401, 0.04085142910480499, 0.018754078075289726, 0.045039739459753036, -0.014978974126279354, -0.04080098867416382, -0.010249467566609383, 0.006752913352102041, 0.09654057770967484, -0.011968614533543587, -0.04467729479074478, -0.010407392866909504, 0.0349593348801136, 0.009787479415535927, 0.009328710846602917, 0.017005180940032005, 0.0708572193980217, 0.02276623621582985, 0.0032521497923880816, 0.009961695410311222, -0.01756301522254944, 0.08088890463113785, -0.005403265357017517, -0.05197016894817352, 0.08331669867038727, -0.009208008646965027, 0.0034990222193300724, 0.00875542126595974, 0.0017162362346425653, 0.007715498562902212, -0.006184863857924938, -0.0016366241034120321, 0.055826082825660706, -0.06490278989076614, -0.025725362822413445, 0.016385214403271675, 0.005793420597910881, -0.0019275146769359708, 0.004402210935950279, -0.0002784222306217998, -0.01760261133313179, -0.05944977328181267, 0.08486047387123108, -0.0023625001776963472, -0.013542208820581436, -0.02311318926513195, -0.04112439230084419, 0.005502136889845133, 0.02608976885676384, 0.028773918747901917, 0.01158441137522459, 0.026982126757502556, -0.04289819672703743, 0.05340943858027458, 0.03674072027206421, -0.03998708724975586, 0.0012832583161070943, 0.006360950414091349, -0.024500899016857147, -0.019748874008655548, -0.015199650079011917, -0.0009323851554654539, 0.03368760645389557, 0.010290472768247128, 0.004956631921231747, 0.00808174628764391, 0.014626022428274155, 0.04153380170464516, -0.0008978266268968582, 0.04631119593977928, -0.05480653792619705, -0.05699692294001579, -0.011297676712274551, -0.07164543122053146, 0.005811348557472229, 0.06546840816736221, -0.016690917313098907, 0.023806268349289894, -0.05009666457772255, 0.06502895057201385, 0.008151358924806118, -0.007974307052791119, 0.04633381590247154, 0.040609609335660934, -0.08629944175481796, 0.0066996607929468155, 0.006348644383251667, -0.08009025454521179, 0.02002338506281376, 0.007803876418620348, -0.05282360315322876, 0.04625936597585678, 0.0034049535170197487, 0.009727445431053638, 0.014723720028996468, -0.021802987903356552, -0.04983498901128769, -0.014571815729141235, 0.012312325648963451, -0.04910650849342346, 0.015172556973993778, 0.056048814207315445, 0.031435612589120865, -0.024076350033283234, 0.0017189639620482922, 0.008655768819153309, 0.05533833056688309, -0.008122238330543041, -0.0010118435602635145, -0.03022143244743347, 0.04293382167816162, -0.006939170882105827, -0.059422094374895096, 0.02897719107568264, 0.010791493579745293, 0.023759977892041206, -0.04489482566714287, 0.025561895221471786, -0.035697244107723236, 0.03028072603046894, -0.010160114616155624, -0.07301510125398636, -0.02503134123980999, 0.012284481897950172, 0.01421144139021635, 0.05717581883072853, 0.0013604710111394525, -0.00896795466542244, -0.06725519150495529, 0.013664920814335346, 0.032917167991399765, 0.004932872951030731, -0.038463737815618515, -0.027995511889457703, -0.0358504056930542, -0.02610388956964016, -0.03649860620498657, 0.013387334533035755, -0.04476122558116913, 0.023420080542564392, -0.025231873616576195, -0.067982979118824, -0.008064781315624714, -0.01545645110309124, -0.020287586376070976, 0.008361211977899075, 0.034544602036476135, 0.02875843271613121, 0.005591452121734619, -0.00926963984966278, -0.028502751141786575, 0.04625162482261658, -0.08213558793067932, -0.03792789578437805, -0.03359387069940567, 0.04839175194501877, -0.039407528936862946, 0.001985035138204694, 0.007802687119692564, 0.011952999047935009, -0.048036862164735794, -0.032479435205459595, -0.04186788946390152, 0.01756972074508667, 0.042349886149168015, 0.04119594395160675, -0.05567247048020363, -0.0291573628783226, 0.03823051229119301, -0.010214668698608875, -0.03371995687484741, 0.020422983914613724, -0.01193165872246027, 0.02438797987997532, -0.016014862805604935, 0.01978147216141224, -0.0032467336859554052, 0.015272838994860649, -0.01048706378787756, 0.04358857870101929, -0.04045439139008522, 0.007065956946462393, -0.030346259474754333, 0.010144440457224846, -0.0440409891307354, 0.041315849870443344, -0.032865848392248154, 0.03559555858373642, -0.032242003828287125, 0.012523358687758446, 0.02092035301029682, -0.0038760898169130087, 0.02298787795007229, -0.017281843349337578, 0.006314410362392664, -0.06048106774687767, -0.04714806750416756, -0.04318500682711601, 0.02157481014728546, 0.006154091563075781, -0.02159062586724758, -0.014314603991806507, 0.01607780158519745, 0.058461543172597885, -0.02695007435977459, -0.0014237880241125822, 0.011463787406682968, 0.06272317469120026, 0.022153006866574287, -0.004364388063549995, 0.04445161670446396, 0.0974414125084877, -0.028136758133769035, 0.04679110646247864, 0.06666305661201477, 0.031344909220933914, 0.012225749902427197, 0.0016543350648134947, -0.04510046914219856, 0.004833315499126911, -0.030295787379145622, -0.04648289829492569, -0.03967202454805374, 0.0029764187056571245, -0.047406844794750214, 0.02242041938006878, -0.0038775820285081863, -0.006260502152144909, 0.0392717644572258, -0.051529884338378906, -0.049376439303159714, -0.07532277703285217, -0.012905722483992577, 0.04355725273489952, 0.056461043655872345, -0.029997464269399643, -0.004649150650948286, -0.019796881824731827, 0.007154363673180342, -0.007882170379161835, -0.012983974069356918, -0.03381502628326416, -0.017579274252057076, -0.030218830332159996, -0.047073230147361755, 0.01564687304198742, -0.02823157049715519, 0.010404352098703384, -0.014692660421133041, 0.00040759105468168855, -0.023364346474409103, 0.007503433618694544, -0.037938278168439865, -0.003064855234697461, -0.04871149733662605, -0.015835367143154144, 0.01002936065196991, 0.01310003362596035, 0.038587432354688644, -0.06895275413990021, -0.015591572038829327, -0.03900862857699394, 0.027705635875463486, -0.049277164041996, 0.03020208142697811, 0.0064261723309755325, 0.05062032490968704, 0.0036791549064219, 0.03354821354150772, -0.0037673332262784243, -0.036820754408836365, 0.010964235290884972, -0.008558941073715687, -0.02049235627055168, -0.0017941984115168452, -0.034398842602968216, 0.0213641244918108, 0.03566252067685127, 0.028508055955171585, -0.03765510767698288, -0.04589839652180672, -0.02640225552022457, 0.013492758385837078, 0.024094097316265106, -0.045479800552129745, -0.04712199419736862, -0.04228506237268448, 0.007950824685394764, -0.001321889809332788, 0.04749447852373123, -0.05649513751268387, 0.038203854113817215, -0.03692161291837692, -0.01378862839192152, -0.025005724281072617, -0.0032757525332272053, 0.012689498253166676, -0.041053179651498795, 0.02346174791455269, -0.0027230686973780394, -0.048392292112112045, -0.07588494569063187, -0.004856915213167667, -0.007172415964305401, 0.05507265403866768, -0.033843252807855606, 0.03461265563964844, -0.0052961623296141624, -0.04100818186998367, -0.03372875973582268, 0.0480879470705986, 0.04419246315956116, -0.029974039644002914, 0.07477956265211105, -0.008041157387197018, -0.03813215345144272, -0.022561686113476753, 0.015905914828181267, 0.021597957238554955, 0.09022855013608932, 0.007952935062348843, 0.06692631542682648, -0.009610315784811974, 0.012515443377196789, -0.03208897262811661, 0.024247827008366585, 0.015720732510089874, -0.00014336338790599257, -0.06214051693677902, -0.04524843767285347, -0.0059632472693920135], payload={'description': 'PNY 256GB PRO Elite Class 10 U3 V30 microSDXC Flash Memory Card - 100MB/s, Class 10, U3, V30, A2, 4K UHD, Full HD, UHS-I, Micro SD & SanDisk MobileMate USB 3.0 microSD Card Reader- SDDR-B531-GN6NN Product 1: Class 10, U3, V30 speed class performance with read speeds up to 100MB/s, and write speeds up to 90MB/s for fast and smooth burst mode HD Photography and 4K Ultra HD Videography Product 1: A2 App Performance enables apps to run directly from the microSD card, delivering faster app launch and performance. A2 provides minimally 4000 IOPS (Read) and 2000 IOPS (Write) Product 1: Record and transfer videos, photos, music, files and more from microSD enabled host devices such as Android smartphones and tablets, action and surveillance cameras, drones, computers and more Product 1: Included SD adapter for compatibility with SD enabled host devices including DSLR cameras, video cameras, desktops, and laptops Product 2: Compact and durable microSD card reader Product 2: Fast UHS-I transfer speeds of up to 170 MB/s Product 2: With USB 3.0, move content up to 10x faster than USB 2.0 readers(2) Product 2: Compatible with USB 3.0 and backwards-compatible with USB 2.0', 'image': 'https://m.media-amazon.com/images/I/31isvCjrHJL._AC_.jpg', 'rating_number': 227, 'price': 31.45, 'average_rating': 4.5, 'parent_asin': 'B08Q27PMFK'}),

In [38]:
len(pointstruct)

50

### Write embedded data to QDrant

In [44]:
qdrant_client.upsert(
    collection_name="Amazon_items_collection1",
    wait=True,
    points=pointstruct
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

#### define function for data retrieval

In [47]:
def retrieve_data(query, top_k=5):
    query_embedding = get_embedding(query)
    search_result = qdrant_client.query_points(
        collection_name="Amazon_items_collection1",
        query=query_embedding,
        limit=top_k
    )
    return search_result

In [48]:
retrieve_data("What kind of charging cords do you offer?", top_k=10).points

[ScoredPoint(id=40, version=1, score=0.7114527, payload={'description': "Light Up iPhone Charger Cable - MFi Certified Apple RGB Light LED Charging Cord.USB A to Lightning Cable for iPhone,iPad,iPod and More (5ft) This is a nice gift:this kind of light up RGB iphone charger cable, children and the elderly will especially like it. It's also suitable to give to friends or to use by yourself, it will be cool! Very Special:Once the charging cable is plugged into the charger, it will alternately emit blue, red,green,purple,yellow,Pink light. It looks glowing and feels superb. Ultra-fast charging:This LED iPhone charger cable supports data transfer speeds of up to 480Mb/s & fast charging speeds of up to 3 amps. Compatible with iPhone 14,13,12, 11, X, 8, 7, 6, 5 series models and iPad, iPod Touch has good compatibility. High-quality materials:The metal shell is used to obtain an excellent grip. The soft and strong PVC wire makes the LED charging cable wear-resistant, and the bending life exceeds 10,000 times. Reduce the trouble of frequently replacing the charging cable. What you will get:1 piece of 5-foot light up iphone charger cable. Providing a 12-month product warranty is enough to prove that we attach importance to quality. If you have a problem in use, customer service will reply you within 24 hours.", 'image': 'https://m.media-amazon.com/images/I/618oYDDY3qL.jpg', 'rating_number': 494, 'price': 16.99, 'average_rating': 4.2, 'parent_asin': 'B0BNQ951N8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=33, version=1, score=0.7114527, payload={'description': "Light Up iPhone Charger Cable - MFi Certified Apple RGB Light LED Charging Cord.USB A to Lightning Cable for iPhone,iPad,iPod and More (5ft) This is a nice gift:this kind of light up RGB iphone charger cable, children and the elderly will especially like it. It's also suitable to give to friends or to use by yourself, it will be cool! Very Special:Once the charging cable is plugged into the charger, it will alternately emit blue, red,green,purple,yellow,Pink light. It looks glowing and feels superb. Ultra-fast charging:This LED iPhone charger cable supports data transfer speeds of up to 480Mb/s & fast charging speeds of up to 3 amps. Compatible with iPhone 14,13,12, 11, X, 8, 7, 6, 5 series models and iPad, iPod Touch has good compatibility. High-quality materials:The metal shell is used to obtain an excellent grip. The soft and strong PVC wire makes the LED charging cable wear-resistant, and the bending life exceeds 10,000 times. Reduce the trouble of frequently replacing the charging cable. What you will get:1 piece of 5-foot light up iphone charger cable. Providing a 12-month product warranty is enough to prove that we attach importance to quality. If you have a problem in use, customer service will reply you within 24 hours.", 'image': 'https://m.media-amazon.com/images/I/618oYDDY3qL.jpg', 'rating_number': 494, 'price': 16.99, 'average_rating': 4.2, 'parent_asin': 'B0BNQ951N8'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=9, version=1, score=0.6800925, payload={'description': 'NVK USB Charger Cable 2 in 1 for Dog Training Collar and Remote, 2.6Ft USB Magnetic Charging and Micro USB Cable 【USB 2-In-1 Charger】: This 2 in 1 dog collar charger can charge the nvk shock collars for dog and remote at the same time, which can save your time. The length of charging cable is 2.6ft 【Fast Charger for E-collar】: The dual charger ensures that your bark collar and remote syncing and charging at the same time. NVK Charger Cable 2 in 1 provides a much faster charging and data exchange than other regular cables, protects your e-collar and remote from damage 【Convenient Design】: Lightweight and slim design, you could put the nvk charging cable in your bag or pockets, convenient to take out , expecially fits for the outside back up charging cord in car or traveling 【Wide Compatibility】: USB charger cable for electric dog collar works with power bank, wall charger, car charger, laptop and PC USB port. It can be a good choice as a shock collar charger replacement when your charging cable was damaged or missing 【What You Get】: 2.6Ft NVK dog collar and remote charger with USB micro and magnetic port, 12-month warranty, friendly customer service and 24 hours prompt reply. Note: When charging the devices at the same time, the display on the NVK remote control will show the charging status of the remote control, but not the charging status of the collar, and the red light on the collar will turn green when charging is completed. The charging plug is NOT included', 'image': 'https://m.media-amazon.com/images/I/419CQJ0W07L._AC_.jpg', 'rating_number': 232, 'price': 19.99, 'average_rating': 4.5, 'parent_asin': 'B09WTM6SP3'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=45, version=1, score=0.6155075, payload={'description': 'SNESH-2 Pack USB-C Female to USB Male Adapter, USB C to USB A Adapter Compatible with Mbook, Notebook, Tablet, Smartphone Such as Samsung Galaxy 🔹(Light & compact) Easy to carry and light weight application and use in many devices such as USB Charger, Laptop, Type C Power bank, Type C cable ✅💯 (Reliable & High QA/QC standard) Reliable and passed through QA/QC test 🔹(Data & charging) Data transfer speeds of up to 480 Mbps between connected devices and supports, up to 3 Amps of power output for charging your devices. Enjoy the fast and safe charging 🔹 (Application &Compatibility) Compatible with laptop, Notebook, tablet, smartphone with a USB Type-C port including Macbook Pro 2017/2018/2019, MacBook Air 2018, Video game Switch, Samsung Galaxy S8/S9 & use Extend storage of your new USB-C smartphones ❌(Limitation)This adapter is not applicable for wireless charger and video signal.', 'image': 'https://m.media-amazon.com/images/I/41bOA5-ogWL._AC_.jpg', 'rating_number': 352, 'price': 4.99, 'average_rating': 4.5, 'parent_asin': 'B09JV5FM2S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=42, version=1, score=0.5950597, payload={'description': 'JOSTART 【4 Pack】 USB C to USB Adapter, USB C Female to USB Male Adapter Compatible with Laptops, PC, Power Adapter, Car Charger etc, for Type-C Phone/Airpods/Samsung/Google etc(Black) 【Important note】-This is a USB C female to USB A male adapter, specially designed for charging and data transfer. 【Simple but powerful】-The usb c to usb adapter enables you to connect USB-C peripherals to devices with built-in USB-A ports. 【Small enough】-Keep it in the USB port without sticking out of your device. 【Safe & Fast】-Usb to usb c adapter provides up to 480 Mbps data transfer speed and also supports up to 2.6A power output. 【Durability】Constructed from durable aluminum alloy to ensure that usb c to a adapter will not wear out over time.', 'image': 'https://m.media-amazon.com/images/I/51b9uQvZMrL._AC_.jpg', 'rating_number': 128, 'price': 7.66, 'average_rating': 4.4, 'parent_asin': 'B0B715Y19L'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=43, version=1, score=0.59458154, payload={'description': 'Upgraded Wii Remote Controller Charger Station, Covanm 4 Port Wii Charging Station with 4 Rechargeable Battery for Wii (4 Port Charging Station+4 Replacement Batteries+USB Cable+Free USB Wall Charger 4 Port Charging Station -- Designed with 4 charging docks, Compatible with wii remote and allow you to charge 4 Wii controllers at the same time(Romotes are not included). Always be ready for gaming! Warm Tip: Controllers are not included. Bonus High Capacity Batteries Plus USB Wall Charger -- Comes 4 2800mAh batteries, long last batteries’ life. You can always have your Wii remote controller ready for gaming! Individual LED Light Indicator -- Cool indicator light will show the charging state of each battery. Also a WII remote and batteries organizer -- No worries about hard to find your wii remotes or batteries, this Wii charging station can be a station to organize the batteries and wii remotes. Safer if you turn off the electric. Anti-slip Strip -- 2 anti-slip strips are specially designed at the bottom of the Wii charging station to prevent the remote controller from falling down.', 'image': 'https://m.media-amazon.com/images/I/413ib9i9izL._AC_.jpg', 'rating_number': 115, 'price': 20.97, 'average_rating': 4.1, 'parent_asin': 'B09SP7TR4D'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=14, version=1, score=0.5920519, payload={'description': 'Anybay EUQQ Bluetooth Earpiece for Cellphone, Bluetooth V5.11 Headset Wireless Headphone with Noise Cancelin 120H Playtime & Dual LED Digital Display : Wireless ear buds with dual power display show the remaining battery of the case by the number on the screen, and the charging status of headphones by up and down of the LED bar, which will fade when the headphones are fully charged. Audifonos Bluetooth inalambricos with 950mAh charging case have up to 120hrs playback with 11 additional charges, you can get the extra electricity it takes to keep your music going.(Before charging, please remove the protective film from the back of the headphone!) 2023 NEW Bluetooth 5.3 and Auto Pairing : The Q63 wireless Bluetooth earphones uses advanced 2023 new Bluetooth 5.3 technology for lower latency, lower power consumption and faster audio data transfer, and the Bluetooth headphones can automatically connect to previously paired devices with virtually no delay. Designed for Sports : Sport earhook headphones to keep you motivated, a secure fit that won’t shift or fall out during long hours of training, and no wires to hold you back. Equipped with 3 pairs of ear caps and flexible ear hooks, which can stay on your ears and get a suitable fitting. So that you will not feel tired and pain when wearing it for a long time. bluetooth earphones can fit for camping, running, or working out, even on a rainy day. High-fidelity Audio & Crystal-clear Call : Bluetooth ear buds adopt 13 mm drivers and volume-optimized active EQ to keep audio clear and balanced at any volume, and the high compliance diaphragm reproduces a rich bass range, also enhances sound quality and reduces distortion. Mics work together to reduce noises around you, keeping your voice sounding clear \u202ffor fewer distractions during phone calls. Bluetooth technology provides a\u202fstrong, consistent connection to your device within 30 feet. Dual Volume Control : Each bluetooth earbud has independent volume and track controls so you could adjust your music without reaching your phone even when you use one earbud alone as independent mode. Equipped with advanced chip, These earbuds with microphones provides stereo sound with deep bass and clear treble.3', 'image': 'https://m.media-amazon.com/images/I/5198hwilCyL._AC_.jpg', 'rating_number': 181, 'price': None, 'average_rating': 4.2, 'parent_asin': 'B0BJ38MN8S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=41, version=1, score=0.5825203, payload={'description': '4 Pairs Galaxy Buds Live Ear Tips Ear Hooks Kit Set, Small/Large 2 Size Silicone Anti-Slip Fit in Case Rubber Ear Buds Wings Eartips Compatible with Samsung Galaxy Buds Live - Mystic Bronze 【 Compatibility 】 Compatible with Samsung Galaxy Buds Live. 【 Material 】 Made of soft flexible premium silicone, provide more noise isolation, in-ear stability and a lasting comfort. And They are Water-washable, durable, flexible, removable and replaceable. 【 Fit in Charge Case 】Fit in the charge Case, not need to remove before put in the case for charge. 【 Nice Sound Quality 】 These ear tips can offer a good seal to reduce some of the outside noise and allow you to focus on your audio, provide a better sound listening experience. 【 Two Size, Storage Box 】 Small and Large 2 different sizes, 2 pairs ear tips and 2 pairs ear hooks, complies comfortably with your individual ear shape. Equipped with a storage box for storing 4 pairs ear tips, which can well protect unused ear buds from being lost or soiled, ear tips only, earphone and charging case NOT included.', 'image': 'https://m.media-amazon.com/images/I/41+Jk-9gMaL._AC_.jpg', 'rating_number': 125, 'price': 6.99, 'average_rating': 4.2, 'parent_asin': 'B0BJ1STN9X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=39, version=1, score=0.54822916, payload={'description': 'INPHIC Wireless Mouse Pink, 2.4G USB Rechargeable Wireless Mice Silent Click, Cute Portable Ergonomic Computer Cordless Mouse for Laptop Mac MacBook 【GODDESS COLOR & CUTE】If you are tired of the normal mouse, inphic pink wireless mouse can be a good choice for you. The pink color matching looks goddess and cute. The small and portable design makes it easy to store in our bags. 【RECHARGEABLE MOUSE】Inphic rechargeable wireless mouse features a built-in 500mAh rechargeable battery and, just 2-3 hours of charging, it will last for 1-2 months. The optimized TYPE-C charging port can be blindly inserted, more convenient for daily use. 【2.4G & 3 ADJUSTABLE DPI】This USB mouse comes with an USB nano receiver stored in the back, just plug it into your computer and you are ready to go. With a powerful and reliable connection up to 33ft. 3 Adjustable DPI levels (800/1200/1600), set your own cursor speed. 【ULTRA-SILENT & ERGONOMIC】This mouse is designed ultra-silent (left & right button) and reduce 90% noise. With a curved & heightened design and delicate matte texture, the ergonomic mouse fits comfortably in the palm of our hands. 【COMPATIBILITY & WARRANTY】Inphic computer mice are compatible with desktop, laptop, tablet, mobile phone, MacBook, iPad, and supports Windows 7/8/10/Mac/iOS/Android and more. Moreover, Inphic offers a 100% worry-free 12-month warranty.', 'image': 'https://m.media-amazon.com/images/I/31kHqyjr9cL._AC_.jpg', 'rating_number': 513, 'price': 10.99, 'average_rating': 4.5, 'parent_asin': 'B0BG3BVY6P'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=26, version=1, score=0.5478655, payload={'description': "6 Pairs Airpod Pro Ear Tip Noise Cancellation, Replacement Ear Tips for Airpods Pro 2 with Case, Soft Silicone Earbuds Tips for Long Time Use, White, S/M/L ✔[COMFORTABLE TO WEAR] The Airpod pro ear tips are made of superior quality silicone material, pleasant and soft, and super light weight. 3 different sizes can meet the different needs of you and your family, so that you can use them for a long time without the feeling of ear pain, even when exercising, it won't slip off. ✔[Advanced Process] Produced by an advanced one-time molding process, with the same noise reduction hole as the original earplug, built-in dustproof mesh, without any welding or bonding steps, longer service life and stronger quality. With noise reduction function, to maintain the original headphones of the best noise reduction effect. ✔[FLAWLESS INSTALLATION] The installation process is simple and quick, and the connection to the earbuds is also tight and seamless. It perfectly matches Airpods Pro 1 generation and Airpods Pro 2 generation, and fits the original AirPods Pro charging case. ✔[STORAGE BOX] We are equipped with a storage box that allows you to store 6 pairs of ear tips, 4* small, 4* medium, and 4* large, which is good for protecting unused earplugs from being lost or smudged. ✔[Customer Service] We will continue to develop more professional and ergonomic ear pads. If you have a problem with the product you purchased, please contact us for a replacement or refund and we will give you a satisfactory solution.", 'image': 'https://m.media-amazon.com/images/I/41HKa7MaYJL._AC_.jpg', 'rating_number': 153, 'price': 5.99, 'average_rating': 4.3, 'parent_asin': 'B0BHHD3JV7'}, vector=None, shard_key=None, order_value=None)]